const TASKS = [
  { id: "math-operations", title: "Szybki rachunek", subject: "Matematyka", description: "Rozwiąż 3 działania w pamięci.", time: "5 min", goal: "Rozgrzewka", difficulty: "Łatwy", points: 10 },
  { id: "polish-reading", title: "Jedno zdanie o tekście", subject: "Język polski", description: "Przeczytaj akapit i zapisz jego główną myśl.", time: "5 min", goal: "Czytanie", difficulty: "Łatwy", points: 10 },
  { id: "english-words", title: "3 słowa po angielsku", subject: "Angielski", description: "Poznaj 3 słowa i ułóż z nimi krótkie zdania.", time: "5 min", goal: "Słownictwo", difficulty: "Łatwy", points: 10 },
  { id: "history-fact", title: "Historyczny fakt", subject: "Historia", description: "Znajdź jeden fakt i opowiedz go własnymi słowami.", time: "5 min", goal: "Ciekawość", difficulty: "Łatwy", points: 10 },
  { id: "nature-observe", title: "Oko badacza", subject: "Przyroda", description: "Obserwuj coś żywego przez minutę i zapisz jedną cechę.", time: "5 min", goal: "Obserwacja", difficulty: "Łatwy", points: 10 },
  { id: "geography-map", title: "Kierunki świata", subject: "Geografia", description: "Wskaż północ, południe, wschód i zachód na mapie.", time: "5 min", goal: "Orientacja", difficulty: "Łatwy", points: 10 },
  { id: "computer-files", title: "Bezpieczny plik", subject: "Informatyka", description: "Wymyśl silne hasło i zapisz, co czyni je bezpiecznym.", time: "5 min", goal: "Bezpieczeństwo", difficulty: "Łatwy", points: 10 },
  { id: "logic-pattern", title: "Wzór liczb", subject: "Logika", description: "Uzupełnij: 2, 4, 6, __ i wyjaśnij dlaczego.", time: "5 min", goal: "Myślenie", difficulty: "Łatwy", points: 10 },
  { id: "math-fractions", title: "Ułamek pizzy", subject: "Matematyka", description: "Narysuj pizzę podzieloną na 4 części i zaznacz 3/4.", time: "7 min", goal: "Wyobraźnia", difficulty: "Średni", points: 20 },
  { id: "polish-parts", title: "Słowa w zdaniu", subject: "Język polski", description: "W jednym zdaniu znajdź rzeczownik, czasownik i przymiotnik.", time: "7 min", goal: "Gramatyka", difficulty: "Średni", points: 20 },
  { id: "english-dialogue", title: "Mini dialog", subject: "Angielski", description: "Napisz 4 linijki dialogu: Hello, How are you?, Fine.", time: "7 min", goal: "Mówienie", difficulty: "Średni", points: 20 },
  { id: "history-timeline", title: "Kolejność wydarzeń", subject: "Historia", description: "Ułóż 3 znane wydarzenia na własnej osi czasu.", time: "7 min", goal: "Porządek", difficulty: "Średni", points: 20 },
  { id: "nature-experiment", title: "Mała hipoteza", subject: "Przyroda", description: "Przewidź, co stanie się z kostką lodu w ciepłym miejscu.", time: "7 min", goal: "Badanie", difficulty: "Średni", points: 20 },
  { id: "geography-climate", title: "Pogoda czy klimat?", subject: "Geografia", description: "Wyjaśnij jednym zdaniem różnicę między pogodą a klimatem.", time: "7 min", goal: "Rozumienie", difficulty: "Średni", points: 20 },
  { id: "computer-algorithm", title: "Instrukcja krok po kroku", subject: "Informatyka", description: "Zapisz 5 kroków przygotowania kanapki jak algorytm.", time: "7 min", goal: "Planowanie", difficulty: "Średni", points: 20 },
  { id: "logic-sudoku", title: "Zagadka dedukcyjna", subject: "Logika", description: "Rozwiąż prostą zagadkę: co nie pasuje do szeregu i dlaczego?", time: "7 min", goal: "Dedukcja", difficulty: "Średni", points: 20 },
  { id: "math-equations", title: "Tajemnicza liczba", subject: "Matematyka", description: "Ułóż równanie, w którym x + 7 = 15, i znajdź x.", time: "10 min", goal: "Rozumowanie", difficulty: "Trudny", points: 40 },
  { id: "polish-argument", title: "Mój argument", subject: "Język polski", description: "Napisz 3 zdania: opinia, argument i przykład.", time: "10 min", goal: "Wypowiedź", difficulty: "Trudny", points: 40 },
  { id: "english-story", title: "Story in 5 sentences", subject: "Angielski", description: "Napisz krótką historię po angielsku z początkiem i zakończeniem.", time: "10 min", goal: "Kreatywność", difficulty: "Trudny", points: 40 },
  { id: "history-source", title: "Kto i kiedy?", subject: "Historia", description: "Sprawdź autora i datę wybranego źródła historycznego.", time: "10 min", goal: "Źródła", difficulty: "Trudny", points: 40 },
  { id: "geography-data", title: "Czytamy wykres", subject: "Geografia", description: "Porównaj na wykresie dwie temperatury lub dwie odległości.", time: "10 min", goal: "Dane", difficulty: "Trudny", points: 40 },
  { id: "computer-web", title: "Pomysł na stronę", subject: "Informatyka", description: "Narysuj makietę strony z nagłówkiem, obrazkiem i przyciskiem.", time: "10 min", goal: "Projektowanie", difficulty: "Trudny", points: 40 },
  { id: "logic-deduction", title: "Mistrz wskazówek", subject: "Logika", description: "Rozwiąż zagadkę logiczną, zapisując każdą wskazówkę.", time: "10 min", goal: "Strategia", difficulty: "Trudny", points: 40 },
  { id: "mixed-review", title: "Powtórka tygodnia", subject: "Powtórka", description: "Wybierz 3 rzeczy, których nauczyłeś się w tym tygodniu.", time: "10 min", goal: "Samodzielność", difficulty: "Trudny", points: 40 }
];

const QUIZ_QUESTIONS = [
  { question: "Ile to jest 7 × 8?", answers: ["54", "56", "64", "48"], correct: "56", explanation: "7 grup po 8 to 56." },
  { question: "Która planeta jest najbliżej Słońca?", answers: ["Mars", "Wenus", "Merkury", "Jowisz"], correct: "Merkury", explanation: "Merkury krąży najbliżej Słońca." },
  { question: "Jak nazywa się osoba opowiadająca wydarzenia w utworze?", answers: ["Narrator", "Bohater", "Autor", "Redaktor"], correct: "Narrator", explanation: "Narrator opowiada wydarzenia; nie zawsze jest ich bohaterem." },
  { question: "What is the opposite of ‘hot’?", answers: ["Warm", "Cold", "Fast", "Big"], correct: "Cold", explanation: "Hot means gorący, a cold means zimny." },
  { question: "W którym kierunku zachodzi Słońce?", answers: ["Na wschodzie", "Na północy", "Na zachodzie", "Na południu"], correct: "Na zachodzie", explanation: "Słońce pozornie zachodzi po zachodniej stronie nieba." },
  { question: "Ile boków ma sześciokąt?", answers: ["5", "6", "7", "8"], correct: "6", explanation: "Przedrostek sześcio- podpowiada liczbę sześciu boków." },
  { question: "Jak nazywa się najdłuższa rzeka w Polsce?", answers: ["Odra", "Wisła", "Warta", "Bug"], correct: "Wisła", explanation: "Wisła ma około 1047 km długości." },
  { question: "Co oznacza skrót CPU?", answers: ["Pamięć", "Procesor", "Dysk", "Monitor"], correct: "Procesor", explanation: "CPU to centralna jednostka obliczeniowa komputera." },
  { question: "Ile wynosi 1/2 + 1/4?", answers: ["1/6", "2/6", "3/4", "1"], correct: "3/4", explanation: "1/2 to 2/4, więc 2/4 + 1/4 = 3/4." },
  { question: "Który gaz jest niezbędny ludziom do oddychania?", answers: ["Tlen", "Azot", "Hel", "Wodór"], correct: "Tlen", explanation: "Komórki wykorzystują tlen do uwalniania energii." }
];
const TRUTH_QUESTIONS = [
  { question: "Woda zamarza w temperaturze 0°C.", correct: true, explanation: "W normalnych warunkach woda zamarza w temperaturze 0°C." },
  { question: "Stolicą Australii jest Sydney.", correct: false, explanation: "Stolicą Australii jest Canberra, nie Sydney." },
  { question: "Trójkąt ma zawsze trzy boki.", correct: true, explanation: "To właśnie trzy boki definiują trójkąt." },
  { question: "HTML jest językiem programowania.", correct: false, explanation: "HTML to język znaczników opisujący strukturę strony." },
  { question: "Ziemia krąży wokół Słońca.", correct: true, explanation: "Ziemia obiega Słońce w około 365 dni." }
];
const MEMORY_PAIRS = [{ pair: "sun", label: "Słońce", match: "Gwiazda", icon: "☀️" }, { pair: "water", label: "Woda", match: "H₂O", icon: "💧" }, { pair: "triangle", label: "Trójkąt", match: "3 boki", icon: "🔺" }, { pair: "cpu", label: "CPU", match: "Procesor", icon: "💻" }, { pair: "book", label: "Książka", match: "Wiedza", icon: "📖" }, { pair: "leaf", label: "Liść", match: "Roślina", icon: "🍃" }];
const STORAGE_KEYS = { completedTasks: "planLekcji.completedTasks.v3", quiz: "planLekcji.quizCompleted.v3", quizPoints: "planLekcji.quizPoints.v3", memory: "planLekcji.memoryCompleted.v3", memoryPoints: "planLekcji.memoryPoints.v3", truth: "planLekcji.truthCompleted.v3", truthPoints: "planLekcji.truthPoints.v3", profile: "planLekcji.profile.v3", today: "planLekcji.today.v3" };
const UNLOCK_XP = { "Łatwy": 0, "Średni": 30, "Trudny": 80 };
let activeFilter = "all"; let gameType = "quiz"; let gameQuestions = []; let gameIndex = 0; let gameScore = 0; let gameStreak = 0; let gameAnswered = false; let memoryCards = []; let memoryOpen = []; let memoryMatched = []; let memoryAttempts = 0; let toastTimeout;
const $ = selector => document.querySelector(selector);
function safeGet(key) { try { return localStorage.getItem(key); } catch { return null; } }
function safeSet(key, value) { try { localStorage.setItem(key, value); return true; } catch { showToast("Nie udało się zapisać postępu."); return false; } }
function readJson(key, fallback) { try { const parsed = JSON.parse(localStorage.getItem(key)); return Array.isArray(parsed) ? parsed : fallback; } catch { return fallback; } }
function completedTaskIds() { return readJson(STORAGE_KEYS.completedTasks, []).filter(id => TASKS.some(task => task.id === id)); }
function boolValue(key) { return safeGet(key) === "true"; }
function numberValue(key) { const value = Number(safeGet(key)); return Number.isFinite(value) && value >= 0 ? value : 0; }
function taskXP(ids = completedTaskIds()) { return TASKS.filter(task => ids.includes(task.id)).reduce((sum, task) => sum + task.points, 0); }
function totalXP() { return taskXP() + numberValue(STORAGE_KEYS.quizPoints) + numberValue(STORAGE_KEYS.memoryPoints) + numberValue(STORAGE_KEYS.truthPoints); }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[character])); }
function shuffle(items) { return [...items].sort(() => Math.random() - 0.5); }
function difficultyClass(difficulty) { return difficulty === "Średni" ? "medium" : difficulty === "Trudny" ? "hard" : ""; }
function levelData(xp) { const level = Math.floor(xp / 50) + 1; const rank = level >= 5 ? "Legenda" : level >= 4 ? "Mistrz" : level >= 2 ? "Praktyk" : "Odkrywca"; return { level, rank, next: level * 50 }; }
function profileData() { return { boy: { name: "Młody odkrywca", avatar: "🧑‍🚀" }, girl: { name: "Młoda odkrywczyni", avatar: "👩‍🚀" }, none: { name: "Odkrywca", avatar: "⭐" } }[safeGet(STORAGE_KEYS.profile) || "none"]; }
function todayProgress() { const saved = readJson(STORAGE_KEYS.today, {}); const date = new Date().toISOString().slice(0, 10); return saved.date === date ? saved.count || 0 : 0; }
function renderProfile() { const current = safeGet(STORAGE_KEYS.profile) || "none"; document.querySelectorAll(".profile-option").forEach(button => button.classList.toggle("selected", button.dataset.profile === current)); const data = profileData(); $("#headerProfile").textContent = `${data.avatar} ${data.name}`; }
function renderSubjects() { const subjects = ["Wszystkie", ...new Set(TASKS.map(task => task.subject))]; $("#subjectChips").innerHTML = subjects.map(subject => `<button class="subject-chip ${subject === "Wszystkie" ? "active" : ""}" data-subject="${escapeHtml(subject)}" type="button">${escapeHtml(subject)}</button>`).join(""); document.querySelectorAll(".subject-chip").forEach(button => button.addEventListener("click", () => { document.querySelectorAll(".subject-chip").forEach(item => item.classList.remove("active")); button.classList.add("active"); renderTasks(button.dataset.subject); })); }
function renderStats() { const ids = completedTaskIds(); const xp = totalXP(); const level = levelData(xp); const percent = TASKS.length ? ids.length / TASKS.length * 100 : 0; $("#completedValue").textContent = `${ids.length} / ${TASKS.length}`; $("#pointsValue").textContent = xp; $("#levelValue").textContent = level.level; $("#rankValue").textContent = level.rank; $("#progressBar").style.width = `${percent}%`; $(".progress").setAttribute("aria-valuenow", String(Math.round(percent))); $("#todayStreak").textContent = `Dziś: ${todayProgress()}`; $("#progressCaption").textContent = ids.length ? `${Math.round(percent)}% planu za Tobą — świetny rytm!` : "Pierwszy krok czeka na Ciebie"; $("#nextLevel").textContent = `Następny poziom za ${Math.max(0, level.next - xp)} XP`; const missingHard = Math.max(0, UNLOCK_XP["Trudny"] - xp); $("#unlockHint").textContent = missingHard ? `Średnie misje od 30 XP · trudne od 80 XP · wybierz tylko tyle, ile masz dziś siły (${missingHard} XP do trudnych)` : "Wszystkie poziomy są odblokowane — wybierz misję dla siebie!"; const games = [{ key: "quiz", label: "quizStatus", points: "quizPoints" }, { key: "memory", label: "memoryStatus", points: "memoryPoints" }, { key: "truth", label: "truthStatus", points: "truthPoints" }]; games.forEach(game => { $("#" + game.label).textContent = boolValue(STORAGE_KEYS[game.key]) ? `✓ Ukończone · +${numberValue(STORAGE_KEYS[game.points])} XP` : "Bonus dostępny"; $("#start" + game.key.charAt(0).toUpperCase() + game.key.slice(1) + "Button").disabled = boolValue(STORAGE_KEYS[game.key]); }); }
function renderTasks(subject = "Wszystkie") { const ids = completedTaskIds(); const visible = TASKS.filter(task => { const done = ids.includes(task.id); const statusOk = activeFilter === "completed" ? done : activeFilter === "open" ? !done : true; return statusOk && (subject === "Wszystkie" || task.subject === subject); }); if (!visible.length) { $("#tasksGrid").innerHTML = '<div class="empty-state"><span>🌱</span><strong>Ten widok jest jeszcze pusty</strong><p>Wybierz inną zakładkę i znajdź małą misję dla siebie.</p></div>'; return; } const xp = totalXP(); $("#tasksGrid").innerHTML = visible.map((task, index) => { const done = ids.includes(task.id); const locked = !done && xp < UNLOCK_XP[task.difficulty]; const missing = UNLOCK_XP[task.difficulty] - xp; return `<article class="task-card ${done ? "completed" : ""} ${locked ? "locked" : ""}" style="animation-delay:${index * 45}ms"><div class="task-number">${String(TASKS.indexOf(task) + 1).padStart(2, "0")}</div><div class="task-content"><div class="task-heading"><div><h3 class="task-title">${escapeHtml(task.title)}</h3><span class="task-subject">${escapeHtml(task.subject)} · ${escapeHtml(task.goal)}</span></div><span class="difficulty ${difficultyClass(task.difficulty)}">${escapeHtml(task.difficulty)}</span></div><p class="task-description">${escapeHtml(task.description)}</p><div class="task-meta"><span class="task-time">⏱ ${escapeHtml(task.time)}</span><span class="xp">+${task.points} XP</span>${done ? '<button class="complete-button" disabled>✓ Gotowe</button>' : locked ? `<span class="lock-note">🔒 Jeszcze ${missing} XP</span>` : `<button class="complete-button" data-task-id="${escapeHtml(task.id)}" type="button">Zrobiłem</button>`}</div></div></article>`; }).join(""); document.querySelectorAll(".complete-button[data-task-id]").forEach(button => button.addEventListener("click", () => completeTask(button.dataset.taskId))); }
function render() { renderProfile(); renderStats(); renderSubjects(); renderTasks(); }
function completeTask(taskId) { const ids = completedTaskIds(); const task = TASKS.find(item => item.id === taskId); if (!task || ids.includes(taskId)) return; if (totalXP() < UNLOCK_XP[task.difficulty]) { showToast(`Ta misja odblokuje się po zdobyciu ${UNLOCK_XP[task.difficulty]} XP.`); return; } safeSet(STORAGE_KEYS.completedTasks, JSON.stringify([...ids, taskId])); const date = new Date().toISOString().slice(0, 10); const old = readJson(STORAGE_KEYS.today, {}); safeSet(STORAGE_KEYS.today, JSON.stringify({ date, count: old.date === date ? (old.count || 0) + 1 : 1 })); showToast(`+${task.points} XP · ${task.time} dobrze zaplanowanej nauki!`); render(); }
function showToast(message) { const toast = $("#toast"); clearTimeout(toastTimeout); toast.textContent = message; toast.classList.add("visible"); toastTimeout = setTimeout(() => toast.classList.remove("visible"), 2800); }
function setFilter(filter) { activeFilter = filter; document.querySelectorAll(".filter-button").forEach(button => button.classList.toggle("active", button.dataset.filter === filter)); const selected = document.querySelector(".subject-chip.active")?.dataset.subject || "Wszystkie"; renderTasks(selected); }
function resetProgress() { if (!confirm("Czy na pewno chcesz wyzerować cały postęp i profil?")) return; Object.values(STORAGE_KEYS).forEach(key => { try { localStorage.removeItem(key); } catch {} }); showToast("Zaczynamy od nowa — wybierz swój profil!"); render(); }
function openGame(type) { gameType = type; gameIndex = 0; gameScore = 0; gameStreak = 0; gameAnswered = false; memoryOpen = []; memoryMatched = []; memoryAttempts = 0; $("#gameModal").classList.remove("hidden"); if (type === "memory") setupMemory(); else { gameQuestions = shuffle(type === "quiz" ? QUIZ_QUESTIONS : TRUTH_QUESTIONS); renderQuestion(); } }
function closeGame() { $("#gameModal").classList.add("hidden"); }
function renderQuestion() { const current = gameQuestions[gameIndex]; $("#modalKicker").textContent = gameType === "quiz" ? "MISJA: QUIZ" : "MISJA: FAKT CZY FIKCJA"; $("#gameScore").textContent = `${gameScore} pkt`; $("#gameProgress span").style.width = `${(gameIndex / gameQuestions.length) * 100}%`; $("#gameProgress").setAttribute("aria-label", `Pytanie ${gameIndex + 1} z ${gameQuestions.length}`); $("#modalTitle").textContent = current.question; $("#gameInstruction").textContent = gameType === "quiz" ? "Pomyśl chwilę. Po odpowiedzi zobaczysz krótkie wyjaśnienie." : "Nie zgaduj na chybił-trafił — poszukaj wskazówki w zdaniu."; const answers = gameType === "quiz" ? shuffle(current.answers).map(answer => ({ label: answer, value: answer })) : [{ label: "Prawda", value: "true" }, { label: "Fałsz", value: "false" }]; $("#gameStage").innerHTML = `<div class="answers">${answers.map(answer => `<button class="answer-button" data-answer="${escapeHtml(answer.value)}" type="button">${escapeHtml(answer.label)}</button>`).join("")}</div>`; $("#gameMessage").textContent = ""; document.querySelectorAll(".answer-button").forEach(button => button.addEventListener("click", () => answerQuestion(button.dataset.answer))); }
function answerQuestion(value) { if (gameAnswered) return; gameAnswered = true; const current = gameQuestions[gameIndex]; const correct = gameType === "quiz" ? value === current.correct : value === String(current.correct); const buttons = document.querySelectorAll(".answer-button"); buttons.forEach(button => { button.disabled = true; const isCorrectButton = gameType === "quiz" ? button.dataset.answer === current.correct : button.dataset.answer === String(current.correct); if (isCorrectButton) button.classList.add("correct"); }); if (!correct) [...buttons].find(button => button.dataset.answer === value)?.classList.add("wrong"); if (correct) { gameScore += 1; gameStreak += 1; } else gameStreak = 0; $("#gameScore").textContent = `${gameScore} pkt · seria ${gameStreak}`; $("#gameMessage").innerHTML = `<span class="feedback ${correct ? "feedback-good" : "feedback-help"}">${correct ? "Dobrze!" : "Spróbuj zapamiętać:"}</span> ${escapeHtml(current.explanation)}<button id="nextGameButton" class="next-button" type="button">${gameIndex + 1 === gameQuestions.length ? "Zobacz wynik" : "Następne pytanie"} <span aria-hidden="true">→</span></button>`; $("#nextGameButton").addEventListener("click", () => { gameIndex += 1; gameAnswered = false; gameIndex < gameQuestions.length ? renderQuestion() : finishQuizLikeGame(); }); }
function finishQuizLikeGame() { const max = gameType === "quiz" ? 50 : 25; const earned = Math.round(gameScore / gameQuestions.length * max); const completedKey = gameType === "quiz" ? "quiz" : "truth"; const pointsKey = gameType === "quiz" ? "quizPoints" : "truthPoints"; $("#gameProgress span").style.width = "100%"; $("#modalKicker").textContent = "MISJA UKOŃCZONA"; $("#modalTitle").textContent = `${gameType === "quiz" ? "Quiz" : "Fakt czy fikcja"}: ${gameScore}/${gameQuestions.length}`; $("#gameStage").innerHTML = `<div class="result-card"><div class="result-stars">${gameScore >= gameQuestions.length * .8 ? "🌟" : "💪"}</div><strong>${gameScore >= gameQuestions.length * .8 ? "Świetna robota!" : "Dobra próba!"}</strong><span>Każda odpowiedź pomaga Ci zapamiętać więcej.</span></div>`; const already = boolValue(STORAGE_KEYS[completedKey]); $("#gameMessage").innerHTML = already ? "Ta gra była już zaliczona wcześniej. Możesz ćwiczyć dalej bez dodatkowego bonusu." : `Zdobywasz <strong>${earned} XP</strong>!`; if (!already) { safeSet(STORAGE_KEYS[completedKey], "true"); safeSet(STORAGE_KEYS[pointsKey], String(earned)); showToast(`+${earned} XP · wiedza zostaje z Tobą!`); renderStats(); renderTasks(); } }
function setupMemory() { const pairCards = shuffle(MEMORY_PAIRS.flatMap(item => [{ ...item, kind: "term", text: item.label }, { ...item, kind: "match", text: item.match }])); memoryCards = pairCards; $("#modalKicker").textContent = "MISJA: LABORATORIUM PAR"; $("#modalTitle").textContent = "Połącz pojęcie z jego znaczeniem"; $("#gameInstruction").textContent = "Odkrywaj dwie karty. Szukaj par: pojęcie + pasujące wyjaśnienie."; $("#gameScore").textContent = "0 par"; $("#gameProgress span").style.width = "0%"; $("#gameStage").innerHTML = `<div class="memory-board">${memoryCards.map((card, index) => `<button class="memory-card" data-index="${index}" type="button" aria-label="Zakryta karta ${index + 1}"><span class="memory-inner"><span class="memory-front">?</span><span class="memory-back"><b>${card.icon}</b><small>${escapeHtml(card.text)}</small></span></span></button>`).join("")}</div>`; $("#gameMessage").textContent = "6 par · bez limitu czasu"; document.querySelectorAll(".memory-card").forEach(card => card.addEventListener("click", () => flipMemory(Number(card.dataset.index)))); }
function flipMemory(index) { if (memoryOpen.length >= 2 || memoryMatched.includes(index) || memoryOpen.includes(index)) return; memoryOpen.push(index); document.querySelector(`[data-index="${index}"]`).classList.add("flipped"); if (memoryOpen.length < 2) return; memoryAttempts += 1; const first = memoryCards[memoryOpen[0]]; const second = memoryCards[memoryOpen[1]]; const match = first.pair === second.pair && first.kind !== second.kind; if (match) { memoryMatched.push(...memoryOpen); memoryOpen = []; $("#gameScore").textContent = `${memoryMatched.length / 2} par`; $("#gameMessage").textContent = "Para znaleziona! Pamięć pracuje świetnie."; $("#gameProgress span").style.width = `${memoryMatched.length / memoryCards.length * 100}%`; if (memoryMatched.length === memoryCards.length) finishMemory(); } else { $("#gameMessage").textContent = "Jeszcze chwila — zapamiętaj położenie kart."; setTimeout(() => { memoryOpen.forEach(cardIndex => document.querySelector(`[data-index="${cardIndex}"]`)?.classList.remove("flipped")); memoryOpen = []; }, 800); } }
function finishMemory() { const earned = Math.max(10, 30 - Math.max(0, memoryAttempts - MEMORY_PAIRS.length) * 2); const already = boolValue(STORAGE_KEYS.memory); $("#modalKicker").textContent = "LABORATORIUM UKOŃCZONE"; $("#modalTitle").textContent = `Znalazłeś wszystkie ${MEMORY_PAIRS.length} par!`; $("#gameStage").innerHTML = `<div class="result-card"><div class="result-stars">🧩✨</div><strong>Pamięć wyćwiczona</strong><span>Prób: ${memoryAttempts} · świetna koncentracja!</span></div>`; $("#gameMessage").innerHTML = already ? "Tę grę ukończono już wcześniej." : `Zdobywasz <strong>${earned} XP</strong>!`; if (!already) { safeSet(STORAGE_KEYS.memory, "true"); safeSet(STORAGE_KEYS.memoryPoints, String(earned)); showToast(`+${earned} XP · para za parą!`); renderStats(); renderTasks(); } }

document.querySelectorAll(".filter-button").forEach(button => button.addEventListener("click", () => setFilter(button.dataset.filter))); document.querySelectorAll(".profile-option").forEach(button => button.addEventListener("click", () => { safeSet(STORAGE_KEYS.profile, button.dataset.profile); renderProfile(); showToast("Profil zapisany — miło Cię widzieć!"); })); $("#resetButton").addEventListener("click", resetProgress); $("#startQuizButton").addEventListener("click", () => openGame("quiz")); $("#startMemoryButton").addEventListener("click", () => openGame("memory")); $("#startTruthButton").addEventListener("click", () => openGame("truth")); $("#closeGameButton").addEventListener("click", closeGame); $("#gameModal").addEventListener("click", event => { if (event.target.id === "gameModal") closeGame(); }); document.addEventListener("keydown", event => { if (event.key === "Escape") closeGame(); });
render();
