/* Plan lekcji — offline, bez zewnętrznych usług. */
const S = {
  tasks: 'planLekcji.completedTasks.v4', lessons: 'planLekcji.completedLessons.v1', profile: 'planLekcji.profile.v4',
  religion: 'planLekcji.showReligion.v1', quiz: 'planLekcji.quiz.v4', quizXp: 'planLekcji.quizXp.v4',
  memory: 'planLekcji.memory.v4', memoryXp: 'planLekcji.memoryXp.v4', truth: 'planLekcji.truth.v4', truthXp: 'planLekcji.truthXp.v4',
  legacyXp: 'planLekcji.legacyXp.v1', legacyCoins: 'planLekcji.legacyCoins.v1', legacyWardrobe: 'planLekcji.legacyWardrobe.v1',
  customPlan: 'planLekcji.customPlan.v1', notebook: 'planLekcji.notebook.v1', sound: 'planLekcji.sound.v1', season: 'planLekcji.season.v1',
  progress: 'planLekcji.progress.v5', preferences: 'planLekcji.preferences.v1', farm: 'planLekcji.farm.v1', homestead: 'planLekcji.homestead.v1'
};

const TIMES = [['07:10','07:55'],['08:00','08:45'],['08:50','09:35'],['09:45','10:30'],['10:40','11:25'],['11:45','12:30'],['12:45','13:30'],['13:35','14:20'],['14:25','15:10'],['15:15','16:00']];
const DEFAULT_DAYS = [
  {key:'mon',short:'Pon',name:'Poniedziałek',lessons:[['08:50','09:35','Język angielski','A. Czerwień-Łętocha','5','📘'],['09:45','10:30','Język polski','M. Dziadkowiec','5','📖'],['10:40','11:25','Edukacja zdrowotna','M. Kalemba','6','💚'],['11:45','12:30','Informatyka','A. Nowak','7','💻'],['12:45','13:30','Zajęcia z wychowawcą','M. Brożek','5','🤝']]},
  {key:'tue',short:'Wt',name:'Wtorek',lessons:[['08:50','09:35','Język angielski','A. Czerwień-Łętocha','5','📘'],['09:45','10:30','Język polski','M. Dziadkowiec','8','📖'],['10:40','11:25','Język polski','M. Dziadkowiec','8','📖'],['11:45','12:30','Matematyka','A. Strużyńska','9','🔢'],['12:45','13:30','Religia','J. Małota','10','🕊️','optional'],['13:35','14:20','Wychowanie fizyczne','M. Brożek','sala gimn.','⚽'],['14:25','15:10','Wychowanie fizyczne','M. Brożek','sala gimn.','⚽']]},
  {key:'wed',short:'Śr',name:'Środa',lessons:[['08:50','09:35','Przyroda','M. Kalemba','5','🌿'],['09:45','10:30','Przyroda','M. Kalemba','5','🌿'],['10:40','11:25','Wychowanie fizyczne','M. Brożek','sala gimn.','⚽'],['11:45','12:30','Wychowanie fizyczne','M. Brożek','sala gimn.','⚽'],['12:45','13:30','Matematyka','A. Strużyńska','9','🔢'],['13:35','14:20','Plastyka','R. Alicki','10','🎨']]},
  {key:'thu',short:'Czw',name:'Czwartek',lessons:[['08:00','08:45','Muzyka','R. Alicki','8','🎵'],['08:50','09:35','Matematyka','A. Strużyńska','9','🔢'],['09:45','10:30','Historia','M. Zawada','6','🏛️'],['10:40','11:25','Język polski','M. Dziadkowiec','8','📖'],['11:45','12:30','Zajęcia Praktyczno-Techniczne','A. Maślak','9','🛠️'],['12:45','13:30','Zajęcia Praktyczno-Techniczne','A. Maślak','9','🛠️']]},
  {key:'fri',short:'Pt',name:'Piątek',lessons:[['08:00','08:45','Język angielski','A. Czerwień-Łętocha','świetlica','📘'],['08:50','09:35','Język polski','M. Dziadkowiec','świetlica','📖'],['09:45','10:30','Przyroda (na zmianę z Edukacją zdrowotną)','M. Kalemba','8','🌿'],['10:40','11:25','Matematyka','A. Strużyńska','9','🔢']]}
];
const DAYS = JSON.parse(JSON.stringify(DEFAULT_DAYS));

const exercise = (question, hint, answer = '') => ({ question, hint, answer });
const task = (id, title, subject, desc, time, xp, diff, unlock, exercises) => ({ id, title, subject, desc, time, xp, diff, unlock, exercises });
const TASKS = [
  task('math','Szybki rachunek','Matematyka','Trzy krótkie działania w pamięci.','5 min',10,'Łatwy',0,[exercise('Oblicz: 36 + 27 = …','Rozbij 27 na 20 i 7.','63'),exercise('Oblicz: 84 − 39 = …','Od 84 odejmij najpierw 40, potem dodaj 1.','45'),exercise('Oblicz: 7 × 8 = …','Pomyśl o siedmiu grupach po osiem.','56')]),
  task('polish','Jedno zdanie o tekście','Język polski','Ćwiczenie głównej myśli tekstu.','5 min',10,'Łatwy',0,[exercise('Przeczytaj krótki akapit z książki i zapisz: kto lub co jest jego bohaterem?','Szukaj osoby, miejsca albo zjawiska, o którym autor mówi najwięcej.'),exercise('Napisz jedno zdanie: „Ten tekst jest głównie o…”.','Nie streszczaj każdego szczegółu.'),exercise('Podkreśl w tekście dwa słowa, które potwierdzają Twoją odpowiedź.','Dowód można znaleźć w samym tekście.')]),
  task('english','3 słowa po angielsku','Angielski','Słowa: book, window, happy.','5 min',10,'Łatwy',0,[exercise('Dopasuj: book, window, happy — do polskich znaczeń.','book = książka, window = okno, happy = szczęśliwy.'),exercise('Ułóż zdanie ze słowem „book”.','Zacznij od I have… albo This is…'),exercise('Ułóż zdanie ze słowem „happy”.','Możesz napisać: I am happy because…')]),
  task('history','Historyczny fakt','Historia','Poznaj fakt i ułóż pytania badacza.','5 min',10,'Łatwy',0,[exercise('Wybierz wydarzenie z podręcznika i zapisz, kiedy się odbyło.','Szukaj daty w nagłówku lub osi czasu.'),exercise('Zapisz, kto brał w nim udział.','To może być osoba, grupa ludzi lub państwo.'),exercise('Ułóż pytanie zaczynające się od „Dlaczego…?”.','Dobre pytanie nie ma odpowiedzi tak/nie.')]),
  task('nature','Oko badacza','Przyroda','Krótka obserwacja czegoś żywego.','5 min',10,'Łatwy',0,[exercise('Wybierz roślinę, zwierzę lub owada, który jest w pobliżu.','Nie dotykaj nieznanych organizmów.'),exercise('Zapisz trzy cechy, które widzisz.','Pomyśl o kolorze, kształcie, ruchu lub miejscu.'),exercise('Napisz jedno pytanie, które chciał(a)byś o nim zbadać.','Np. „Czego potrzebuje do życia?”')]),
  task('geography','Kierunki świata','Geografia','Ćwiczenie z mapą i stronami świata.','5 min',10,'Łatwy',0,[exercise('Na mapie wskaż północ.','Na większości map północ znajduje się u góry.'),exercise('Dopisz przeciwne kierunki do: północ i wschód.','Przeciwieństwa to południe oraz zachód.'),exercise('Napisz: w którą stronę świata jest zachód Słońca?','Słońce zachodzi na zachodzie.')]),
  task('computer','Bezpieczny plik','Informatyka','Poznaj zasady bezpiecznego hasła i plików.','5 min',10,'Łatwy',0,[exercise('Wymień dwie rzeczy, których nie wpiszesz do nazwy pliku.','Nie używaj danych osobowych ani haseł.'),exercise('Zapisz przykład bezpiecznej nazwy pliku.','Np. „projekt_przyroda_v1”.'),exercise('Wyjaśnij, dlaczego hasła nie udostępnia się znajomym.','Hasło chroni konto i prywatność.')]),
  task('logic','Wzór liczb','Logika','Odkrywaj reguły w ciągach.','5 min',10,'Łatwy',0,[exercise('Uzupełnij: 2, 4, 6, …, 10','Za każdym razem dodajesz 2.','8'),exercise('Uzupełnij: 15, 12, 9, …, 3','Za każdym razem odejmujesz 3.','6'),exercise('Wymyśl własny ciąg z jedną prostą zasadą.','Zapisz też, jaka jest zasada.')]),
  task('fraction','Ułamek pizzy','Matematyka','Rysowanie i porównywanie ułamków.','7 min',20,'Średni',25,[exercise('Narysuj koło podzielone na 4 równe części. Zamaluj 3.','Każda część to jedna czwarta.'),exercise('Zapisz ułamek pokazujący zamalowaną część.','Licznik mówi, ile części wybrano.','3/4'),exercise('Który ułamek jest większy: 1/2 czy 1/4?','Porównaj wielkość jednej części.','1/2')]),
  task('dialogue','Mini dialog','Angielski','Cztery linijki rozmowy po angielsku.','7 min',20,'Średni',25,[exercise('Napisz przywitanie: „Hello, …”.','Może być Hello, Anna!'),exercise('Dodaj pytanie: „How are you?”.','Pamiętaj o znaku zapytania.'),exercise('Dopisz odpowiedź i pożegnanie.','Np. I am fine, thank you. Bye!')]),
  task('climate','Pogoda czy klimat?','Geografia','Rozróżnij zjawisko krótkie i długie.','7 min',20,'Średni',25,[exercise('Zdecyduj: „Dziś pada deszcz” — pogoda czy klimat?','To opis jednego dnia.','pogoda'),exercise('Zdecyduj: „Zimy w tym regionie są zwykle chłodne” — pogoda czy klimat?','To obserwacja z wielu lat.','klimat'),exercise('Zapisz własny przykład zdania o klimacie.','Użyj słów: zwykle, przez wiele lat albo średnio.')]),
  task('algorithm','Instrukcja krok po kroku','Informatyka','Stwórz algorytm bez komputera.','7 min',20,'Średni',25,[exercise('Wybierz czynność, np. przygotowanie plecaka.','Czynność powinna mieć wyraźny początek i koniec.'),exercise('Zapisz co najmniej pięć kroków we właściwej kolejności.','Każdy krok powinien zaczynać się od czasownika.'),exercise('Sprawdź, czy ktoś mógłby wykonać instrukcję bez dopytywania.','Dopisz brakujący szczegół, jeśli trzeba.')]),
  task('equation','Tajemnicza liczba','Matematyka','Równania z jedną niewiadomą.','10 min',40,'Trudny',70,[exercise('Rozwiąż: x + 7 = 15','Od obu stron odejmij 7.','8'),exercise('Rozwiąż: 3x = 21','Podziel obie strony przez 3.','7'),exercise('Sprawdź jedno rozwiązanie, podstawiając je do równania.','Lewa i prawa strona powinny dać ten sam wynik.')]),
  task('argument','Mój argument','Język polski','Zbuduj opinię, argument i przykład.','10 min',40,'Trudny',70,[exercise('Wybierz temat: „Czy warto czytać codziennie?”. Zapisz swoją opinię.','Zacznij od: „Uważam, że…”.'),exercise('Podaj argument zaczynający się od „Ponieważ…”.','Argument wyjaśnia, dlaczego tak uważasz.'),exercise('Dodaj konkretny przykład, który wzmacnia argument.','Może dotyczyć Ciebie, książki albo znanej sytuacji.')]),
  task('story','Story in 5 sentences','Angielski','Krótka opowieść z początkiem i zakończeniem.','10 min',40,'Trudny',70,[exercise('Napisz zdanie o bohaterze: „One day, …”.','Wybierz człowieka lub zwierzę.'),exercise('Napisz trzy zdania: co się wydarzyło i jak bohater zareagował.','Przydadzą się czasowniki: found, saw, went, helped.'),exercise('Zakończ zdaniem zaczynającym się od „Finally, …”.','Opowieść powinna mieć zakończenie.')]),
  task('source','Kto i kiedy?','Historia','Oceniaj podstawowe informacje o źródle.','10 min',40,'Trudny',70,[exercise('Wybierz zdjęcie, artykuł lub fragment podręcznika. Zapisz tytuł.','Tytuł zwykle jest na górze źródła.'),exercise('Znajdź autora lub instytucję, która przygotowała materiał.','Jeśli nie ma autora, sprawdź wydawcę.'),exercise('Zapisz datę publikacji albo wyjaśnij, że jej nie podano.','Data pomaga ocenić aktualność źródła.')]),
  task('addition-bridge','Most przez dziesiątki','Matematyka','Dodawanie z przekroczeniem progu dziesiętnego.','6 min',12,'Łatwy',0,[exercise('Oblicz: 48 + 16','Do 48 dodaj 2, aby mieć 50, a potem jeszcze 14.','64'),exercise('Oblicz: 67 + 25','Najpierw 67 + 20, potem +5.','92'),exercise('Narysuj własne działanie z wynikiem większym od 100.','Sprawdź wynik dodawaniem pisemnym lub kalkulatorem po rozwiązaniu.')]),
  task('division-check','Dzielenie i sprawdzenie','Matematyka','Dzielenie oraz mnożenie kontrolne.','7 min',20,'Średni',25,[exercise('Oblicz: 72 : 8','Pomyśl: 8 razy ile daje 72?','9'),exercise('Oblicz: 96 : 12','12 × 8 = 96.','8'),exercise('Sprawdź: 63 : 7 = 9 przez mnożenie.','Pomnóż iloraz przez dzielnik.','7 × 9 = 63')]),
  task('calendar','Mistrz kalendarza','Matematyka','Odczytywanie dat, czasu i dni tygodnia.','6 min',12,'Łatwy',0,[exercise('Jeśli dziś jest wtorek, jaki dzień będzie za 3 dni?','Policz: środa 1, czwartek 2, piątek 3.','piątek'),exercise('Ile minut mija od 8:15 do 9:00?','Od 8:15 do 8:60 jest 45 minut.','45'),exercise('Zapisz godzinę rozpoczęcia i zakończenia jednej lekcji z planu.','Sprawdź zakładkę Plan.')]),
  task('reading-clues','Tropiciel wskazówek','Język polski','Szukaj dowodów w tekście.','7 min',20,'Średni',25,[exercise('Wybierz akapit i podkreśl wyraz, który mówi, gdzie toczy się akcja.','Szukaj nazwy miejsca albo przyimka.'),exercise('Podkreśl wyraz, który mówi, kiedy coś się wydarzyło.','Może to być pora dnia, data lub określenie czasu.'),exercise('Napisz zdanie: „Wiem to, ponieważ w tekście jest…”.','Zacytuj jedno–dwa słowa, nie musisz kopiować całego zdania.')]),
  task('parts-speech','Łowca części mowy','Język polski','Rozpoznawanie rzeczowników, czasowników i przymiotników.','8 min',20,'Średni',25,[exercise('W zdaniu „Wesoły kot szybko biegnie” znajdź rzeczownik.','Rzeczownik nazywa osobę, zwierzę, rzecz lub zjawisko.','kot'),exercise('W tym samym zdaniu znajdź czasownik.','Czasownik odpowiada na pytanie: co robi?','biegnie'),exercise('W tym samym zdaniu znajdź przymiotnik.','Przymiotnik opisuje rzeczownik.','wesoły')]),
  task('description','Opis miejsca','Język polski','Stwórz opis z użyciem zmysłów.','10 min',40,'Trudny',70,[exercise('Wybierz miejsce, które dobrze znasz. Zapisz trzy rzeczy, które w nim widzisz.','Użyj konkretnych rzeczowników.'),exercise('Dopisz jedno zdanie o dźwięku lub zapachu.','Pomogą słowa: słychać, pachnie, cicho, głośno.'),exercise('Napisz zakończenie mówiące, jak się tam czujesz.','Np. „Lubię to miejsce, ponieważ…”.')]),
  task('english-colors','Kolory i rzeczy','Angielski','Opisuj przedmioty kolorami.','6 min',12,'Łatwy',0,[exercise('Przetłumacz: red, green, blue.','To kolejno czerwony, zielony, niebieski.'),exercise('Napisz zdanie: „The book is …”.','Wstaw dowolny kolor.'),exercise('Rozejrzyj się i zapisz po angielsku dwa kolorowe przedmioty.','Możesz użyć: a red pen, a blue bag.')]),
  task('english-routine','Mój dzień po angielsku','Angielski','Czasowniki codziennych czynności.','8 min',20,'Średni',25,[exercise('Połącz: get up, eat breakfast, go to school — z polskimi znaczeniami.','Wstać, jeść śniadanie, iść do szkoły.'),exercise('Napisz zdanie: „I get up at …”.','Użyj godziny, która pasuje do Ciebie.'),exercise('Napisz dwa kolejne zdania o swoim poranku.','Możesz zacząć od: Then I…')]),
  task('map-symbols','Mapa pełna znaków','Geografia','Czytaj legendę i symbole mapy.','6 min',12,'Łatwy',0,[exercise('Znajdź legendę na wybranej mapie.','Legenda wyjaśnia znaczenie znaków.'),exercise('Zapisz znaczenie dwóch symboli.','Wybierz np. rzekę, drogę, las lub miasto.'),exercise('Wyjaśnij, dlaczego mapa nie pokazuje wszystkiego w prawdziwym rozmiarze.','Mapa jest pomniejszonym modelem terenu.')]),
  task('continents','Kontynenty i oceany','Geografia','Utrwal nazwy na mapie świata.','8 min',20,'Średni',25,[exercise('Wymień siedem kontynentów.','Europa, Azja, Afryka, Ameryka Północna, Ameryka Południowa, Australia, Antarktyda.'),exercise('Wskaż na mapie Ocean Atlantycki.','Leży między Amerykami a Europą i Afryką.'),exercise('Zapisz, na którym kontynencie leży Polska.','Szukaj w północnej części Europy.','Europa')]),
  task('water-cycle','Obieg wody','Przyroda','Poznaj drogę kropli wody.','7 min',20,'Średni',25,[exercise('Ułóż kolejność: parowanie, skraplanie, opad.','Słońce ogrzewa wodę, para tworzy chmury, potem pada deszcz.'),exercise('Wyjaśnij, co dzieje się z kałużą w ciepły dzień.','Woda może zamieniać się w parę.'),exercise('Narysuj trzy strzałki pokazujące obieg wody.','Podpisz każdą strzałkę.')]),
  task('food-chain','Łańcuch pokarmowy','Przyroda','Kto kogo zjada w naturze?','8 min',20,'Średni',25,[exercise('Ułóż: trawa, królik, lis.','Strzałka pokazuje, skąd zwierzę czerpie energię.','trawa → królik → lis'),exercise('Jak nazywa się organizm, który sam wytwarza pokarm?','Roślina jest producentem.','producent'),exercise('Wymyśl drugi łańcuch z trzema ogniwami.','Zacznij od rośliny.')]),
  task('plants','Detektyw roślin','Przyroda','Części rośliny i ich funkcje.','6 min',12,'Łatwy',0,[exercise('Wymień cztery części typowej rośliny.','Korzeń, łodyga, liść, kwiat.'),exercise('Która część pobiera wodę z ziemi?','Jest zwykle ukryta pod ziemią.','korzeń'),exercise('Napisz, do czego roślinie potrzebne są liście.','W liściach zachodzi fotosynteza.')]),
  task('timeline','Oś czasu','Historia','Porządkuj wydarzenia od najstarszego.','7 min',20,'Średni',25,[exercise('Ustaw na osi: 1990, 2005, 2018.','Najmniejsza data jest najwcześniej.','1990, 2005, 2018'),exercise('Ile lat minęło między 2005 a 2018?','Odejmij mniejszą liczbę od większej.','13'),exercise('Zapisz trzy ważne wydarzenia z własnego życia w kolejności.','Możesz użyć roku urodzenia, rozpoczęcia szkoły i obecnego roku.')]),
  task('art-colors','Kolory mówią','Plastyka','Sprawdź, jak kolor zmienia nastrój pracy.','6 min',12,'Łatwy',0,[exercise('Wybierz kolor, który kojarzy Ci się ze spokojem.','Nie ma jednej poprawnej odpowiedzi.'),exercise('Wybierz kolor, który kojarzy Ci się z energią.','Pomyśl o słońcu, ogniu lub ruchu.'),exercise('Narysuj dwa małe pola z tym samym symbolem w różnych kolorach.','Porównaj ich nastrój.')]),
  task('rhythm','Rytm w ruchu','Muzyka','Odtwarzaj i twórz krótkie rytmy.','6 min',12,'Łatwy',0,[exercise('Wystukaj rytm: klaśnij–klaśnij–pauza–klaśnij.','Rób równe odstępy.'),exercise('Powtórz go dwa razy bez przyspieszania.','Możesz liczyć: 1, 2, 3, 4.'),exercise('Wymyśl własny rytm z czterech uderzeń.','Zapisz go symbolami ● i —.')]),
  task('healthy-choice','Energia na dzień','Edukacja zdrowotna','Zauważ, co pomaga w nauce i odpoczynku.','6 min',12,'Łatwy',0,[exercise('Wymień jedną rzecz, która daje Ci energię rano.','Może to być sen, śniadanie, ruch lub rozmowa.'),exercise('Wymień jedną rzecz, która pomaga Ci odpocząć po nauce.','Nie musi to być ekran.'),exercise('Ułóż własną zasadę: „Dziś zadbam o…”.','Wybierz mały, możliwy krok.')]),
  task('build-bridge','Most z papieru','Technika','Zaprojektuj prostą konstrukcję.','10 min',40,'Trudny',70,[exercise('Narysuj most, który ma utrzymać mały przedmiot.','Zaznacz podpory.'),exercise('Wypisz dwa materiały, których użyjesz.','Np. papier, taśma, patyczki.'),exercise('Napisz, co zmienisz, jeśli most będzie się wyginał.','Możesz dodać zgięcie, podporę albo szerszą podstawę.')])
];

const QUIZ = [
  ['Ile to jest 7 × 8?',['54','56','64','48'],'56','Siedem grup po osiem daje 56.'],['Która planeta jest najbliżej Słońca?',['Mars','Wenus','Merkury','Jowisz'],'Merkury','Merkury krąży najbliżej Słońca.'],['Jak nazywa się osoba opowiadająca wydarzenia?',['Narrator','Bohater','Autor','Redaktor'],'Narrator','Narrator opowiada wydarzenia.'],['What is the opposite of hot?',['Warm','Cold','Fast','Big'],'Cold','Cold znaczy zimny.'],['W którym kierunku zachodzi Słońce?',['Na wschodzie','Na północy','Na zachodzie','Na południu'],'Na zachodzie','Słońce zachodzi po zachodniej stronie nieba.'],['Ile boków ma sześciokąt?',['5','6','7','8'],'6','Sześciokąt ma sześć boków.'],['Najdłuższa rzeka w Polsce to…',['Odra','Wisła','Warta','Bug'],'Wisła','Wisła ma około 1047 km.'],['Co oznacza skrót CPU?',['Pamięć','Procesor','Dysk','Monitor'],'Procesor','CPU to centralna jednostka obliczeniowa.'],['Ile wynosi 1/2 + 1/4?',['1/6','2/6','3/4','1'],'3/4','Jedna druga to dwie czwarte, więc razem są trzy czwarte.'],['Który gaz jest potrzebny do oddychania?',['Tlen','Azot','Hel','Wodór'],'Tlen','Komórki wykorzystują tlen do uwalniania energii.'],['Które słowo jest rzeczownikiem?',['biegnie','zielony','kot','szybko'],'kot','Rzeczownik nazywa osobę, zwierzę, rzecz lub zjawisko.'],['Ile minut ma jedna godzina?',['30','60','90','100'],'60','Godzina to 60 minut.'],['Który kontynent jest największy?',['Europa','Australia','Azja','Afryka'],'Azja','Azja jest największym kontynentem.'],['Jak nazywa się proces zamiany wody w parę?',['Skraplanie','Parowanie','Opad','Zamarzanie'],'Parowanie','Pod wpływem ciepła woda paruje.'],['Które zdanie ma znak zapytania?',['Idę do domu.','Jak masz na imię?','Ale pięknie!','Nie wiem.'],'Jak masz na imię?','Pytanie kończymy znakiem zapytania.']
].map(([q,a,c,e])=>({q,a,c,e}));
const TRUTH = [
  ['Woda zamarza w temperaturze 0°C.',true,'W normalnych warunkach tak.'],['Stolicą Australii jest Sydney.',false,'Stolicą Australii jest Canberra.'],['Trójkąt ma zawsze trzy boki.',true,'Trzy boki definiują trójkąt.'],['HTML jest językiem programowania.',false,'HTML to język znaczników.'],['Ziemia krąży wokół Słońca.',true,'Ziemia obiega Słońce w około 365 dni.'],['Nietoperze są ptakami.',false,'Nietoperze są ssakami.'],['Liście pobierają światło potrzebne roślinie.',true,'W liściach zachodzi fotosynteza.'],['Wszystkie mapy są w tej samej skali.',false,'Różne mapy mogą mieć różne skale.'],['Zdanie zaczynamy wielką literą.',true,'To podstawowa zasada pisowni.'],['12 × 4 to 52.',false,'12 × 4 = 48.']
].map(([q,c,e])=>({q,c,e}));
const PAIRS = [['Słońce','Gwiazda','☀️'],['Woda','H₂O','💧'],['Trójkąt','3 boki','🔺'],['CPU','Procesor','💻'],['Książka','Wiedza','📖'],['Liść','Roślina','🍃'],['Wisła','Rzeka','🌊'],['Mars','Planeta','🔴']];
const WORDS = [{word:'PLANETA',hint:'Krąży wokół gwiazdy.'},{word:'UŁAMEK',hint:'Pokazuje część całości.'},{word:'KONTYNENT',hint:'Bardzo duży obszar lądu.'},{word:'NARRATOR',hint:'Opowiada wydarzenia w tekście.'},{word:'ALGORYTM',hint:'Instrukcja krok po kroku.'},{word:'FOTOSYNTEZA',hint:'Roślina wykorzystuje światło, wodę i dwutlenek węgla.'}];
const SPRINT = [['18 + 24 = ?',['32','42','52','44'],'42','18 + 20 to 38, a +4 daje 42.'],['90 − 37 = ?',['53','63','47','57'],'53','90 − 30 = 60, a 60 − 7 = 53.'],['9 × 6 = ?',['45','54','56','63'],'54','Dziewięć razy sześć to 54.'],['64 : 8 = ?',['6','7','8','9'],'8','8 × 8 = 64.'],['Która liczba jest parzysta?',['15','21','28','33'],'28','Liczba parzysta dzieli się przez 2 bez reszty.'],['1/2 z 20 to…',['5','10','15','20'],'10','Połowa z 20 to 10.'],['3, 6, 9, …',['10','11','12','13'],'12','Kolejna liczba jest większa o 3.'],['100 − 1 = ?',['99','98','101','89'],'99','Od stu odejmujemy jeden.']].map(([q,a,c,e])=>({q,a,c,e}));
const MATH_PETS = [['Ile to jest 24 + 18?',['32','42','52','44'],'42','24 + 10 = 34, a +8 daje 42.'],['Ile to jest 7 × 6?',['36','42','48','56'],'42','Sześć grup po siedem daje 42.'],['Połowa z 30 to…',['10','12','15','20'],'15','Połowa oznacza podzielenie przez 2.'],['Która liczba jest większa?',['27','72','27','17'],'72','Siedem dziesiątek to więcej niż dwie.'],['Jeżyk ma 5 jabłek i dostaje 4. Ile ma razem?',['8','9','10','11'],'9','Dodajemy 5 + 4.']].map(([q,a,c,e])=>({q,a,c,e}));

const SEASONS = {
  auto:{name:'Automatyczny',emoji:'🪄',label:'Auto',description:'Dopasuj do obecnego miesiąca.'},
  winter:{name:'Zimowa Przystań',emoji:'❄️',label:'Zima',description:'Śnieżne kryształki i spokojne tempo.',message:'Zbieraj kryształki wiedzy i ogrzewaj swój szlak codzienną ciekawością.'},
  spring:{name:'Wiosenna Polana',emoji:'🌷',label:'Wiosna',description:'Kwiaty, ptaki i nowe pomysły.',message:'Każdy mały krok może zakwitnąć w nową umiejętność.'},
  summer:{name:'Letnia Wyspa',emoji:'☀️',label:'Lato',description:'Ciepłe kolory i wyspy odkryć.',message:'Łap fale ciekawości i odkrywaj świat w swoim tempie.'},
  autumn:{name:'Jesienny Szlak Wiedzy',emoji:'🍂',label:'Jesień',description:'Liście, las i leśni towarzysze.',message:'Zbieraj liście wiedzy i zapraszaj zwierzęta na swój szlak.'}
};
const ANIMALS = [{id:'owl',name:'Puchacz',emoji:'🦉',threshold:0},{id:'hedgehog',name:'Jeżyk',emoji:'🦔',threshold:45},{id:'fox',name:'Lisek',emoji:'🦊',threshold:110},{id:'otter',name:'Wydra',emoji:'🦦',threshold:230},{id:'deer',name:'Sarenka',emoji:'🦌',threshold:420},{id:'bee',name:'Pszczółka',emoji:'🐝',threshold:700}];
const GAMES = [{id:'farm',icon:'🐾',symbol:'♥',color:'#d87935',label:'GŁÓWNA GRA · 12 PUPILI',title:'Zwierzakowa Farma',desc:'Opiekuj się pupilami, buduj relacje, wysyłaj je na wyprawy i rozwijaj magiczną farmę.'},{id:'homestead',icon:'🌾',symbol:'✦',color:'#a66a2a',label:'GŁÓWNA GRA · 8 ZWIERZĄT',title:'Gospodarstwo',desc:'Zbieraj produkty, rozbudowuj budynki, handluj na rynku i kolekcjonuj rasy.'},{id:'mathpets',icon:'🐾',symbol:'＋',color:'#e29a34',label:'NAGRODY · ZWIERZAKI',title:'Matematyczny Tropiciel',desc:'Rozwiązuj działania i odblokowuj kolejnych towarzyszy na Szlaku Odkrywców.'},{id:'quiz',icon:'🧠',symbol:'✦',color:'#7b5dd0',label:'WIEDZA · 10 PYTAŃ',title:'Misja: Quiz',desc:'Losowe pytania z wielu przedmiotów. Każda odpowiedź ma wyjaśnienie.'},{id:'memory',icon:'🧩',symbol:'✦',color:'#168b88',label:'PAMIĘĆ · 8 PAR',title:'Laboratorium par',desc:'Połącz pojęcie z definicją, obserwuj liczbę prób i bij rekord.'},{id:'truth',icon:'💡',symbol:'?',color:'#cc6384',label:'MYŚLENIE · 10 ZDAŃ',title:'Fakt czy fikcja?',desc:'Sprawdzaj informacje i ucz się krytycznego myślenia.'},{id:'word',icon:'🔤',symbol:'A',color:'#d18d28',label:'SŁOWA · 5 HASEŁ',title:'Słowny trop',desc:'Układaj hasła z rozsypanych liter na podstawie podpowiedzi.'},{id:'sprint',icon:'⚡',symbol:'+',color:'#357cc9',label:'MATEMATYKA · 8 RUND',title:'Szybki sprint',desc:'Krótkie działania, wzory i liczby — bez presji czasu.'}];
const FARM_PETS = {girl:[['Luna','jednorożec','🦄','mądra','legend'],['Fifi','wróżka','🧚','nieśmiała','epic'],['Mia','kotka','🐱','psotna','common'],['Pusia','króliczek','🐰','leniwy','common'],['Motylka','motylek','🦋','energiczna','uncommon'],['Kropka','piesek','🐶','energiczna','common'],['Panda','panda','🐼','spokojna','rare'],['Rudy','lisek','🦊','psotny','uncommon'],['Iskra','smok','🐉','mądry','epic'],['Żar','feniks','🔥','energiczny','legend'],['Perła','syrena','🧜','nieśmiała','rare'],['Skrzydła','pegaz','🪽','mądry','legend']],boy:[['Rex','dinozaur','🦖','energiczny','rare'],['Bolt','robot','🤖','mądry','uncommon'],['Smok','smok','🐉','psotny','epic'],['Wilk','wilk','🐺','nieśmiały','uncommon'],['Rekin','rekin','🦈','energiczny','rare'],['Leo','lew','🦁','mądry','common'],['Tygrys','tygrys','🐯','psotny','uncommon'],['Orzeł','orzeł','🦅','mądry','rare'],['Smoczek','smoczek','🐲','leniwy','common'],['Tyran','tyranozaur','🦕','energiczny','legend'],['Skorupka','żółw','🐢','spokojny','common'],['Ptero','pterodaktyl','🦅','energiczny','epic']]};
const HOMESTEAD_ANIMALS = [['Kury','kura','🐔','jajka',8,0],['Kaczki','kaczka','🦆','jajka',10,60],['Gęsi','gęś','🪿','pióra',12,100],['Indyki','indyk','🦃','pióra',14,140],['Króliki','królik','🐇','wełna',10,180],['Kozy','koza','🐐','mleko',16,260],['Owce','owca','🐑','wełna',18,340],['Krowy','krowa','🐄','mleko',22,480]];
const FARM_TRIPS = [['Las','🌲',300,18],['Jaskinia','🪨',600,35],['Plaża','🏖️',900,50],['Góry','⛰️',1800,90]];

const $ = selector => document.querySelector(selector);
const clear = node => node.replaceChildren();
const make = (tag, className, text) => { const node = document.createElement(tag); if (className) node.className = className; if (text !== undefined) node.textContent = text; return node; };
const button = (text, className, handler) => { const node = make('button', className, text); node.type = 'button'; if (handler) node.addEventListener('click', handler); return node; };
const append = (node, ...children) => { children.flat().filter(Boolean).forEach(child => node.append(child)); return node; };
const get = (key, fallback) => { try { const value = localStorage.getItem(key); return value === null ? fallback : JSON.parse(value); } catch { return fallback; } };
const set = (key, value) => { try { localStorage.setItem(key, JSON.stringify(value)); return true; } catch { toast('Nie udało się zapisać danych na tym urządzeniu.'); return false; } };
const bool = key => localStorage.getItem(key) === 'true';
const shuffle = array => [...array].sort(() => Math.random() - .5);
const clamp = (value, min, max) => Math.min(max, Math.max(min, value));
const dayKey = () => ['sun','mon','tue','wed','thu','fri','sat'][new Date().getDay()];
const toArray = (key) => { const value = get(key, []); return Array.isArray(value) ? value : []; };
const completedLessons = () => toArray(S.lessons);
const completedTasks = () => toArray(S.tasks);

const DEFAULT_PROGRESS = {version:1, gameXp:0, gameHistory:{}, selectedAnimal:'owl', sessionCount:0};
const MIGRATIONS = {1: old => ({...DEFAULT_PROGRESS, ...(old && typeof old === 'object' ? old : {}), version:2, gameHistory: {...DEFAULT_PROGRESS.gameHistory, ...(old?.gameHistory || {})}})};
function migrate(key, fromVer, toVer) { let data = get(key, null); for (let version = fromVer; version < toVer; version += 1) data = MIGRATIONS[version] ? MIGRATIONS[version](data) : data; set(key, data); return data; }
function loadProgress() { const saved = get(S.progress, null); if (!saved || typeof saved !== 'object') { set(S.progress, DEFAULT_PROGRESS); return {...DEFAULT_PROGRESS}; } const version = Number(saved.version) || 1; return migrate(S.progress, version, 2); }
let progress = loadProgress();
let preferences = get(S.preferences, {season:'auto', animations:true});
if (!preferences || typeof preferences !== 'object') preferences = {season:'auto', animations:true};
function saveProgress() { set(S.progress, progress); }
function savePreferences() { set(S.preferences, preferences); }
function migrateLegacyState() {
  const oldIds = get('planLekcji.completedTasks.v3', []);
  if (!localStorage.getItem(S.tasks) && Array.isArray(oldIds)) set(S.tasks, oldIds.filter(id => TASKS.some(item => item.id === id)));
  if (!localStorage.getItem(S.profile) && localStorage.getItem('planLekcji.profile.v3')) set(S.profile, get('planLekcji.profile.v3','none'));
  if (!localStorage.getItem(S.quiz) && bool('planLekcji.quizCompleted.v3')) { set(S.quiz,true); set(S.quizXp,Math.min(50,Number(get('planLekcji.quizPoints.v3',0)))); }
  if (!localStorage.getItem(S.memory) && bool('planLekcji.memoryCompleted.v3')) { set(S.memory,true); set(S.memoryXp,Number(get('planLekcji.memoryPoints.v3',0))); }
  if (!localStorage.getItem(S.truth) && bool('planLekcji.truthCompleted.v3')) { set(S.truth,true); set(S.truthXp,Math.min(25,Number(get('planLekcji.truthPoints.v3',0)))); }
  if (!localStorage.getItem(S.legacyXp)) { const xp = Number(get('plan51_xp',0)) || 0; if (xp > 0) set(S.legacyXp,xp); }
}

function taskXp() { const done = completedTasks(); return TASKS.filter(item => done.includes(item.id)).reduce((sum,item) => sum + item.xp, 0); }
function legacyGameXp() { return Number(get(S.quizXp,0) || 0) + Number(get(S.memoryXp,0) || 0) + Number(get(S.truthXp,0) || 0); }
function totalXp() { return taskXp() + legacyGameXp() + Number(get(S.legacyXp,0) || 0) + Number(progress.gameXp || 0); }
function autoSeason() { const month = new Date().getMonth(); if (month === 11 || month < 2) return 'winter'; if (month < 5) return 'spring'; if (month < 8) return 'summer'; return 'autumn'; }
function currentSeasonKey() { return preferences.season === 'auto' ? autoSeason() : (SEASONS[preferences.season] ? preferences.season : 'autumn'); }
function currentSeason() { return SEASONS[currentSeasonKey()]; }
function unlockedAnimals() { const xp = totalXp(); return ANIMALS.filter(animal => xp >= animal.threshold); }
function selectedAnimal() { const unlocked = unlockedAnimals(); return unlocked.find(animal => animal.id === progress.selectedAnimal) || unlocked[0] || ANIMALS[0]; }
function rewardToday() { return new Date().toISOString().slice(0,10); }
function playTone(kind = 'tap') { if (!bool(S.sound)) return; try { const Ctx = window.AudioContext || window.webkitAudioContext; if (!Ctx) return; const context = new Ctx(); const oscillator = context.createOscillator(); const gain = context.createGain(); oscillator.type = kind === 'wrong' ? 'triangle' : 'sine'; oscillator.frequency.value = kind === 'success' ? 660 : kind === 'wrong' ? 190 : 440; gain.gain.setValueAtTime(.0001, context.currentTime); gain.gain.exponentialRampToValueAtTime(.06, context.currentTime + .01); gain.gain.exponentialRampToValueAtTime(.0001, context.currentTime + .14); oscillator.connect(gain); gain.connect(context.destination); oscillator.start(); oscillator.stop(context.currentTime + .16); } catch {} }
function toast(message) { const node = $('#toast'); node.textContent = message; node.classList.add('visible'); clearTimeout(window.toastTimer); window.toastTimer = setTimeout(() => node.classList.remove('visible'), 2800); }

let selectedDay = dayKey(); if (!DAYS.some(day => day.key === selectedDay)) selectedDay = 'mon';
let activeView = 'plan', activeFilter = 'all', selectedSubject = 'Wszystkie', searchQuery = '', activeTask = null;
let gameState = {type:null, questions:[], index:0, score:0, answered:false, memoryCards:[], memoryOpen:[], memoryMatched:[], attempts:0, wordLetters:[], wordAnswer:'', wordUsed:[]};

function effectiveDays() { const custom = get(S.customPlan, null); if (!Array.isArray(custom) || custom.length !== DAYS.length) return DAYS; return DAYS.map((day,index) => { const candidate = custom[index]; return candidate && candidate.key === day.key && Array.isArray(candidate.lessons) ? candidate : day; }); }
function renderDays() { const root = $('#days'); clear(root); effectiveDays().forEach(day => { const node = button('', `day-tab${day.key === selectedDay ? ' active' : ''}${day.key === dayKey() ? ' today' : ''}`, () => { selectedDay = day.key; renderPlan(); }); node.dataset.day = day.key; node.setAttribute('role','tab'); node.setAttribute('aria-selected', String(day.key === selectedDay)); append(node, make('b','',day.short), make('small','',day.name.slice(0,3))); root.append(node); }); }
function renderPlan() {
  const day = effectiveDays().find(item => item.key === selectedDay) || effectiveDays()[0]; const showReligion = get(S.religion,false); const done = completedLessons();
  const lessons = day.lessons.map((row,index) => ({start:row[0],end:row[1],subject:row[2],teacher:row[3],room:row[4],icon:row[5],optional:row[6] === 'optional',id:`${day.key}-${index}`})).filter(item => showReligion || !item.optional);
  $('#selectedDayTitle').textContent = day.name; $('#dateLabel').textContent = selectedDay === dayKey() ? 'Dzisiaj · sprawdź swój spokojny rytm dnia' : 'Plan na wybrany dzień'; $('#lessonCount').textContent = `${lessons.length} ${lessons.length === 1 ? 'lekcja' : 'lekcji'}`; $('#optionalNote').textContent = showReligion ? 'Pokazujesz także religię. Możesz ją ukryć w zakładce „Więcej”.' : 'Religia jest ukryta. Możesz ją włączyć w zakładce „Więcej”.';
  const list = $('#lessonList'); clear(list);
  if (!lessons.length) { const empty = make('div','empty-state'); append(empty, make('span','', '🌤️'), make('strong','', 'Brak lekcji tego dnia'), make('p','', 'To dobry moment na odpoczynek albo krótką misję.')); list.append(empty); }
  lessons.forEach(lesson => { const finished = done.includes(lesson.id); const card = make('article',`lesson-card${finished ? ' done' : ''}`); const time = make('div','lesson-time'); append(time,make('b','',lesson.start),make('span','',lesson.end)); const body = make('div','lesson-body'); append(body, make('h3','',lesson.subject), make('p','',`${lesson.teacher} · sala ${lesson.room}`)); if (lesson.optional) body.append(make('span','optional-tag','opcjonalne')); const check = button(finished ? '✓' : '○',`lesson-check${finished ? ' checked' : ''}`,() => toggleLesson(lesson.id)); check.setAttribute('aria-label', `${finished ? 'Cofnij' : 'Oznacz'} ukończenie: ${lesson.subject}`); append(card,time,make('div','lesson-icon',lesson.icon),body,check); list.append(card); });
  const completed = lessons.filter(lesson => done.includes(lesson.id)).length; const percent = lessons.length ? completed / lessons.length * 100 : 0; $('#dayProgress').textContent = `${completed} / ${lessons.length}`; $('#dayProgressBar').style.width = `${percent}%`; const next = lessons.find(lesson => !done.includes(lesson.id)); $('#nextLesson').textContent = next ? next.subject : 'Plan zrealizowany!'; $('#nextLessonTime').textContent = next ? `${next.start} · sala ${next.room}` : 'Świetna robota — odpocznij'; renderDays(); renderHeader();
}
function toggleLesson(id) { const before = completedLessons(); const next = before.includes(id) ? before.filter(item => item !== id) : [...before,id]; set(S.lessons,next); playTone(next.length > before.length ? 'success' : 'tap'); toast(before.includes(id) ? 'Lekcja wróciła do planu.' : 'Lekcja oznaczona jako wykonaną!'); renderPlan(); renderProgress(); }
function renderHeader() { const xp = totalXp(); const profile = get(S.profile,'none'); document.body.dataset.playerTheme = profile === 'girl' ? 'girl' : profile === 'boy' ? 'boy' : 'neutral'; $('#headerXp').textContent = `⭐ ${xp} XP`; $('#greeting').textContent = profile === 'girl' ? 'Twój szlak, odkrywczyni' : profile === 'boy' ? 'Twój szlak, odkrywco' : 'Twój szlak na dziś'; document.querySelectorAll('.profile-option').forEach(node => node.classList.toggle('selected',node.dataset.profile === profile)); $('#soundToggle').textContent = bool(S.sound) ? '🔊' : '🔇'; $('#soundToggle').setAttribute('aria-label',bool(S.sound) ? 'Wyłącz dźwięki' : 'Włącz dźwięki'); }
function renderSeason() { const season = currentSeason(); const companion = selectedAnimal(); const xp = totalXp(); const next = ANIMALS.find(animal => animal.threshold > xp); document.body.dataset.season = currentSeasonKey(); document.body.dataset.animations = preferences.animations ? 'on' : 'off'; $('#seasonChip').textContent = `${season.emoji} ${season.label} · ${preferences.season === 'auto' ? 'auto' : 'własny'}`; $('#seasonEmoji').textContent = season.emoji; $('#companionEmoji').textContent = companion.emoji; $('#seasonTitle').textContent = season.name; $('#seasonMessage').textContent = season.message; $('#seasonKicker').textContent = preferences.season === 'auto' ? 'TRYB AUTOMATYCZNY' : 'TWÓJ WYBRANY MOTYW'; $('#seasonProgressBar').style.width = `${next ? clamp((xp - companion.threshold) / (next.threshold - companion.threshold) * 100,0,100) : 100}%`; $('#seasonProgressText').textContent = next ? `${xp} XP · kolejny towarzysz za ${next.threshold - xp} XP` : `${xp} XP · cała kolekcja odblokowana!`; $('#worldTitle').textContent = season.name; $('#worldMessage').textContent = `${season.message} Aktualnie towarzyszy Ci ${companion.name}.`; $('#worldProgressBar').style.width = `${next ? clamp((xp - companion.threshold) / (next.threshold - companion.threshold) * 100,0,100) : 100}%`; $('#worldProgressText').textContent = next ? `${xp} XP · ${next.name} czeka za ${next.threshold - xp} XP` : `${xp} XP · wszystkie zwierzęta są z Tobą`; const art = $('#worldArt'); clear(art); unlockedAnimals().forEach(animal => art.append(make('span','',animal.emoji))); }

function taskVisible(item, done) { const matchesStatus = activeFilter === 'all' || (activeFilter === 'completed' && done) || (activeFilter === 'open' && !done); const matchesSubject = selectedSubject === 'Wszystkie' || item.subject === selectedSubject; const needle = searchQuery.trim().toLocaleLowerCase('pl'); const matchesText = !needle || [item.title,item.subject,item.desc,...item.exercises.map(ex => ex.question)].join(' ').toLocaleLowerCase('pl').includes(needle); return matchesStatus && matchesSubject && matchesText; }
function renderSubjects() { const root = $('#subjectChips'); clear(root); ['Wszystkie',...new Set(TASKS.map(item => item.subject))].forEach(subject => { const node = button(subject,`subject-chip${subject === selectedSubject ? ' active' : ''}`,() => { selectedSubject = subject; renderTasks(); }); root.append(node); }); }
function renderTasks() { const ids = completedTasks(); const visible = TASKS.filter(item => taskVisible(item,ids.includes(item.id))); $('#taskTotal').textContent = String(TASKS.length); $('#libraryResult').textContent = `Pokazujemy ${visible.length} z ${TASKS.length} zestawów · każdy zawiera 3 ćwiczenia.`; const root = $('#tasksGrid'); clear(root); if (!visible.length) { const empty = make('div','empty-state'); append(empty,make('span','', '🔎'),make('strong','', 'Nie znaleziono zestawów'),make('p','', 'Zmień słowo wyszukiwania lub wybierz inny przedmiot.')); root.append(empty); return; }
  visible.forEach(item => { const done = ids.includes(item.id); const locked = !done && totalXp() < item.unlock; const card = make('article',`task-card${done ? ' completed' : ''}${locked ? ' locked' : ''}`); card.style.setProperty('--task-color',item.subject === 'Matematyka' ? '#357cc9' : item.subject === 'Angielski' ? '#a35bbb' : item.subject === 'Przyroda' ? '#3d9b64' : '#d87935'); const heading = make('div','task-heading'); const titleBlock = make('div'); append(titleBlock,make('h3','',item.title),make('span','task-subject',item.subject)); const difficulty = make('span',`difficulty${item.diff === 'Średni' ? ' medium' : item.diff === 'Trudny' ? ' hard' : ''}`,item.diff); append(heading,titleBlock,difficulty); const meta = make('div','task-meta'); meta.append(make('span','',`⏱ ${item.time}`),make('span','xp',`+${item.xp} XP`)); const action = button(done ? '✓ Gotowe' : locked ? `🔒 ${item.unlock} XP` : 'Otwórz zestaw',`complete-button${done ? ' done-button' : ''}`,() => { if (locked) { toast(`Ten zestaw odblokuje się po zdobyciu ${item.unlock} XP.`); playTone('wrong'); } else openTask(item); }); if (done) action.disabled = true; meta.append(action); const content = make('div','task-content'); append(content,heading,make('p','',item.desc),meta); append(card,make('div','task-number',String(TASKS.indexOf(item)+1).padStart(2,'0')),content); root.append(card); }); }
function openTask(item) { activeTask = item; $('#taskModalKicker').textContent = `${item.subject.toUpperCase()} · ${item.diff.toUpperCase()}`; $('#taskModalTitle').textContent = item.title; $('#taskModalIntro').textContent = `${item.desc} Wykonaj po kolei trzy ćwiczenia. Odpowiedzi wpisujesz tylko dla siebie — aplikacja ich nie wysyła i nie zapisuje.`; const stage = $('#taskStage'); clear(stage); stage.classList.remove('show-hints'); item.exercises.forEach((itemExercise,index) => { const line = make('section','task-item'); append(line,make('b','',`${index + 1}. ${itemExercise.question}`)); const input = document.createElement('input'); input.className = 'task-answer'; input.autocomplete = 'off'; input.placeholder = 'Twoja odpowiedź lub notatka…'; input.setAttribute('aria-label',`Odpowiedź do zadania ${index + 1}`); line.append(input); const hint = make('p','task-hint',`Podpowiedź: ${itemExercise.hint}${itemExercise.answer ? ` Oczekiwany wynik: ${itemExercise.answer}.` : ''}`); line.append(hint); stage.append(line); }); $('#taskHintButton').textContent = 'Pokaż podpowiedzi'; $('#taskModal').classList.remove('hidden'); }
function finishTask() { if (!activeTask) return; const ids = completedTasks(); if (!ids.includes(activeTask.id)) { set(S.tasks,[...ids,activeTask.id]); playTone('success'); toast(`+${activeTask.xp} XP · zestaw wykonany!`); } $('#taskModal').classList.add('hidden'); activeTask = null; renderAll(); }

function profileTheme() { const profile = get(S.profile,'none'); return profile === 'girl' ? 'girl' : 'boy'; }
function petDefaults() { return Object.fromEntries(FARM_PETS[profileTheme()].map(([name,species,emoji,personality,rarity],index) => [String(index),{name,species,emoji,personality,rarity,level:1,energy:82,hunger:26,happiness:78,relation:0,health:100,selected:index === 0,photos:0,interactions:0}])); }
function loadFarm() { const saved = get(S.farm,null); const pets = petDefaults(); if (!saved || typeof saved !== 'object') return {version:1,coins:120,selected:'0',pets,trip:null,tripLog:[],items:[],events:[],tutorial:true}; return {...{version:1,coins:120,selected:'0',pets,trip:null,tripLog:[],items:[],events:[],tutorial:false},...saved,pets:{...pets,...(saved.pets || {})}}; }
function loadHomestead() { const saved = get(S.homestead,null); const animals = Object.fromEntries(HOMESTEAD_ANIMALS.map(([name,species,emoji,product,minutes,cost],index) => [String(index),{name,species,emoji,product,minutes,level:1,age:1,unlocked:index === 0,production:0,last:Date.now()}])); if (!saved || typeof saved !== 'object') return {version:1,coins:80,grain:12,basket:[],capacity:10,building:'Kurnik',buildingLevel:1,animals,orders:[],log:['🐔 Kura gotowa do pracy!'],tutorial:true}; return {...{version:1,coins:80,grain:12,basket:[],capacity:10,building:'Kurnik',buildingLevel:1,animals,orders:[],log:[],tutorial:false},...saved,animals:{...animals,...(saved.animals || {})}}; }
let farmState = loadFarm(); let homesteadState = loadHomestead(); let primaryGameTab = 'farm'; let farmTimer = null;
function saveFarm() { set(S.farm,farmState); } function saveHomestead() { set(S.homestead,homesteadState); }
function petMood(pet) { if (pet.health < 50) return ['💔','Potrzebuje opieki']; if (pet.energy < 25) return ['💤','Zmęczony']; if (pet.hunger > 75) return ['🍽️','Głodny']; if (pet.happiness > 75) return ['✨','Szczęśliwy']; return ['😊','Spokojny']; }
function petValue(pet) { const mood = petMood(pet)[1]; const base = 5 + pet.relation * 2 + pet.level; return Math.round(base * (mood === 'Szczęśliwy' ? 1.2 : mood === 'Głodny' ? .6 : 1)); }
function addPrimaryReward(coins,xp,message) { farmState.coins += coins; progress.gameXp += xp; progress.sessionCount += 1; saveFarm(); saveProgress(); toast(`${message} +${coins} 🐾 · +${xp} XP`); playTone('success'); }
function levelPet(pet) { const next = Math.min(10,1 + Math.floor(pet.relation / 2)); if (next > pet.level) { pet.level = next; toast(`${pet.name} awansuje na poziom ${next}!`); } }
function farmAction(action) { const pet = farmState.pets[farmState.selected]; if (!pet) return; if (action === 'feed') { if (farmState.coins < 8) return toast('Potrzebujesz 8 🐾 na smakołyk.'); farmState.coins -= 8; pet.hunger = Math.max(0,pet.hunger - 40); pet.happiness = Math.min(100,pet.happiness + 8); progress.gameXp += 10; toast(`${pet.name} chrupie z radością! +10 XP`); }
  if (action === 'play') { if (pet.energy < 8) return toast(`${pet.name} potrzebuje odpoczynku.`); pet.energy -= 8; pet.happiness = Math.min(100,pet.happiness + 14); pet.relation = Math.min(10,pet.relation + 1); pet.interactions += 1; progress.gameXp += 8; toast(`${pet.name} bawi się z Tobą! +8 XP`); }
  if (action === 'rest') { pet.energy = Math.min(100,pet.energy + 30); pet.happiness = Math.max(0,pet.happiness - 2); toast(`${pet.name} zasypia pod miękkim kocykiem.`); }
  if (action === 'gift') { if (farmState.coins < 25) return toast('Potrzebujesz 25 🐾 na prezent.'); farmState.coins -= 25; pet.happiness = Math.min(100,pet.happiness + 25); pet.relation = Math.min(10,pet.relation + 1); progress.gameXp += 15; toast(`${pet.name} dostał prezent! +15 XP`); }
  if (action === 'photo') { pet.photos += 1; progress.gameHistory.farmPhoto = {sessions:(progress.gameHistory.farmPhoto?.sessions || 0) + 1,best:1,lastReward:rewardToday()}; progress.gameXp += 5; toast(`Zdjęcie ${pet.name} trafiło do albumu!`); }
  if (action === 'heal') { if (pet.health >= 100) return toast(`${pet.name} jest zdrowy.`); if (farmState.coins < 20) return toast('Lekarstwo kosztuje 20 🐾.'); farmState.coins -= 20; pet.health = 100; pet.happiness = Math.min(100,pet.happiness + 10); toast(`${pet.name} znów czuje się świetnie.`); }
  levelPet(pet); saveFarm(); saveProgress(); renderPrimaryGame('farm'); renderSeason(); renderProgress(); }
function startTrip(index) { const pet = farmState.pets[farmState.selected]; const trip = FARM_TRIPS[index]; if (!pet || !trip) return; if (farmState.trip) return toast('Najpierw odbierz zakończoną wyprawę.'); if (pet.energy < 25) return toast(`${pet.name} jest zbyt zmęczony na wyprawę.`); pet.energy -= 20; farmState.trip = {pet:farmState.selected,type:trip[0],emoji:trip[1],ends:Date.now() + trip[2] * 1000,reward:trip[3]}; saveFarm(); renderPrimaryGame('farm'); toast(`${pet.name} rusza na wyprawę: ${trip[0]}!`); startFarmTimer(); }
function collectTrip() { if (!farmState.trip) return; if (Date.now() < farmState.trip.ends) return toast('Wyprawa jeszcze trwa — sprawdź później.'); const reward = farmState.trip.reward + Math.floor(Math.random() * 25); farmState.coins += reward; progress.gameXp += Math.floor(reward / 2); farmState.tripLog.unshift(`${new Date().toLocaleTimeString('pl-PL',{hour:'2-digit',minute:'2-digit'})} · ${farmState.trip.type}: +${reward} 🐾`); if (farmState.tripLog.length > 8) farmState.tripLog.pop(); farmState.trip = null; saveFarm(); saveProgress(); toast(`Wyprawa zakończona! Znaleziono ${reward} 🐾.`); renderPrimaryGame('farm'); renderProgress(); }
function startFarmTimer() { clearInterval(farmTimer); farmTimer = setInterval(() => { if (!farmState.trip) return clearInterval(farmTimer); const timer = $('#primaryTimer'); if (timer) timer.textContent = formatTimer(Math.max(0,farmState.trip.ends - Date.now())); },1000); }
function formatTimer(ms) { const seconds = Math.ceil(ms / 1000); return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2,'0')}`; }
function homesteadPhase() { const hour = new Date().getHours(); return hour < 6 ? ['🌙','Noc',.3] : hour < 12 ? ['🌅','Poranek',1.5] : hour < 18 ? ['☀️','Południe',1] : hour < 22 ? ['🌇','Wieczór',.7] : ['🌙','Noc',.3]; }
function collectAnimal(id) { const animal = homesteadState.animals[id]; if (!animal?.unlocked) return toast('To zwierzę odblokuje się po rozbudowie gospodarstwa.'); const elapsed = Math.max(0,Date.now() - animal.last); const phase = homesteadPhase()[2]; const amount = Math.min(3,Math.floor(elapsed / (animal.minutes * 60000) * phase)); if (!amount) return toast(`${animal.name} potrzebuje jeszcze trochę czasu.`); homesteadState.basket.push(...Array.from({length:amount},() => ({product:animal.product,quality:Math.random() > .9 ? 'wyśmienite' : Math.random() > .6 ? 'dobre' : 'zwykłe',value:animal.product === 'mleko' ? 14 : animal.product === 'wełna' ? 12 : animal.product === 'pióra' ? 9 : 7}))); homesteadState.basket = homesteadState.basket.slice(-homesteadState.capacity); animal.last = Date.now(); homesteadState.log.unshift(`${animal.emoji} ${animal.name} dostarczyły: ${animal.product}`); homesteadState.log = homesteadState.log.slice(0,8); saveHomestead(); renderPrimaryGame('homestead'); }
function collectAllAnimals() { Object.keys(homesteadState.animals).forEach(collectAnimal); toast('Zebrano gotowe produkty do koszyka.'); }
function sellBasket() { if (!homesteadState.basket.length) return toast('Koszyk jest pusty.'); const phase = homesteadPhase()[2]; const value = Math.round(homesteadState.basket.reduce((sum,item) => sum + item.value * (item.quality === 'wyśmienite' ? 3 : item.quality === 'dobre' ? 1.5 : 1),0) * phase); homesteadState.coins += value; homesteadState.basket = []; homesteadState.log.unshift(`🧺 Sprzedano produkty za ${value} 🌾`); progress.gameXp += Math.max(4,Math.floor(value / 10)); saveHomestead(); saveProgress(); toast(`Sprzedano koszyk za ${value} 🌾!`); renderPrimaryGame('homestead'); renderProgress(); }
function unlockAnimal(id) { const animal = homesteadState.animals[id]; const data = HOMESTEAD_ANIMALS[Number(id)]; if (!animal || animal.unlocked) return; if (homesteadState.coins < data[5]) return toast(`Potrzebujesz ${data[5]} 🌾.`); homesteadState.coins -= data[5]; animal.unlocked = true; homesteadState.log.unshift(`🎉 Dołączyły: ${data[0]}!`); saveHomestead(); renderPrimaryGame('homestead'); }
function upgradeHomestead() { const cost = 80 * homesteadState.buildingLevel; if (homesteadState.coins < cost) return toast(`Ulepszenie kosztuje ${cost} 🌾.`); homesteadState.coins -= cost; homesteadState.buildingLevel = Math.min(4,homesteadState.buildingLevel + 1); homesteadState.capacity += 10; homesteadState.building = ['Kurnik','Obora','Stodoła','Farma'][homesteadState.buildingLevel - 1]; homesteadState.log.unshift(`🏠 Rozbudowano budynek: ${homesteadState.building}`); saveHomestead(); toast('Gospodarstwo jest większe!'); renderPrimaryGame('homestead'); }
function gameHistory(type) { return progress.gameHistory[type] || {sessions:0,best:0,lastReward:''}; }
function renderGames() { const root = $('#gamesGrid'); clear(root); GAMES.forEach(game => { const history = gameHistory(game.id); const card = make('article','game-card'); card.dataset.symbol = game.symbol; card.style.setProperty('--game-color',game.color); append(card,make('div','game-icon',game.icon),make('span','game-label',game.label),make('h2','',game.title),make('p','',game.desc)); const status = make('span','game-status', game.id === 'farm' ? `🐾 ${farmState.coins} monet · ${Object.values(farmState.pets).filter(p => p.photos).length} zdjęć` : game.id === 'homestead' ? `🌾 ${homesteadState.coins} monet · ${homesteadState.basket.length}/${homesteadState.capacity} w koszyku` : history.sessions ? `Rekord: ${history.best}/${game.id === 'memory' ? '8' : game.id === 'sprint' ? '8' : game.id === 'word' ? '5' : '10'} · ${history.lastReward === rewardToday() ? 'bonus dzisiaj odebrany' : 'bonus dzisiaj dostępny'}` : 'Pierwsza sesja czeka na Ciebie'); const start = button(game.id === 'farm' || game.id === 'homestead' ? 'Wejdź' : 'Graj', 'play-button', () => openGame(game.id)); append(card,status,start); root.append(card); }); renderAnimals(); }
function progressBar(label,value,color='var(--accent)') { const wrap = make('div','primary-stat'); const top = make('div','primary-stat-top'); append(top,make('b','',label),make('span','',`${Math.round(value)}%`)); const bar = make('div','primary-bar'); const fill = make('span'); fill.style.width = `${clamp(value,0,100)}%`; fill.style.background = color; append(wrap,top,append(bar,fill)); return wrap; }
function primaryHeader(title,subtitle,icon,coins,currency,tab) { const head = make('div','primary-header'); const copy = make('div'); append(copy,make('span','primary-icon',icon),(() => { const c = make('div'); append(c,make('span','eyebrow',tab),make('h2','',title),make('p','',subtitle)); return c; })()); const wallet = make('div','primary-wallet'); append(wallet,make('b','',`${coins} ${currency}`),make('small','',homesteadPhase()[1])); append(head,copy,wallet); return head; }
function renderFarmPanel(stage) { clear(stage); const pet = farmState.pets[farmState.selected] || Object.values(farmState.pets)[0]; const mood = petMood(pet); const profile = profileTheme() === 'girl' ? '✨ Magiczna Dolina' : '🦖 Dino-Polana'; append(stage,primaryHeader('Zwierzakowa Farma',`Opiekuj się pupilami i rozwijaj relację · ${profile}`,'🐾',farmState.coins,'🐾','FARMA · GŁÓWNA GRA')); const tabs = make('div','primary-tabs'); ['Farma','Kolekcja','Wyprawy','Sklep'].forEach(tab => tabs.append(button(tab,`primary-tab${tab === primaryGameTab ? ' active' : ''}`,() => { primaryGameTab = tab.toLowerCase(); renderPrimaryGame('farm'); }))); stage.append(tabs);
  const scene = make('div','farm-scene'); append(scene,make('span','farm-cloud','☁️'),make('span','farm-tree','🌳'),make('span','farm-flower','🌼')); const petCard = make('article','pet-focus'); const portrait = make('div','pet-portrait'); append(portrait,make('span','pet-bubble',mood[0]),make('span','pet-emoji',pet.emoji),make('small','pet-level',`POZIOM ${pet.level}`)); const bio = make('div','pet-bio'); append(bio,make('h3','',`${pet.name} · ${pet.species}`),make('p','',`${pet.personality}. Lubi wspólne chwile i ma własne małe marzenia.`),make('p','pet-dialog',pet.relation >= 6 ? '„Wiem, że zawsze mogę na Ciebie liczyć!”' : '„Pobawimy się? Mam dziś mnóstwo energii!”')); const stats = make('div','pet-stats'); append(stats,progressBar('Energia',pet.energy,'#5a9ce6'),progressBar('Głód',100 - pet.hunger,'#d59a3c'),progressBar('Szczęście',pet.happiness,'#d96a91'),progressBar('Zdrowie',pet.health,'#51a46e')); append(petCard,portrait,bio,stats); scene.append(petCard); stage.append(scene);
  const actions = make('div','pet-actions'); [['feed','🍎 Nakarm'],['play','🎾 Baw się'],['rest','💤 Uśpij'],['gift','🎁 Prezent'],['photo','📸 Zdjęcie'],['heal','🩹 Lecz']].forEach(([action,label]) => actions.append(button(label,'primary-action',() => farmAction(action)))); stage.append(actions);
  if (primaryGameTab === 'kolekcja') { const collection = make('div','pet-collection'); Object.values(farmState.pets).forEach(candidate => { const item = make('button',`pet-tile${candidate.name === pet.name ? ' selected' : ''}`); item.type='button'; item.addEventListener('click',() => { farmState.selected = Object.keys(farmState.pets).find(key => farmState.pets[key].name === candidate.name) || '0'; saveFarm(); renderPrimaryGame('farm'); }); append(item,make('span','',candidate.emoji),make('b','',candidate.name),make('small','',candidate.rarity)); collection.append(item); }); stage.append(collection); }
  if (primaryGameTab === 'wyprawy') { const trips = make('div','trip-grid'); FARM_TRIPS.forEach((trip,index) => { const card = make('article','trip-card'); const active = farmState.trip?.type === trip[0]; append(card,make('span','trip-icon',trip[1]),make('b','',trip[0]),make('small','',`${Math.floor(trip[2]/60)} min · nagroda od ${trip[3]} 🐾`),button(active ? 'Sprawdź' : 'Wyślij pupila','primary-action',() => active ? collectTrip() : startTrip(index))); trips.append(card); }); stage.append(trips); if (farmState.trip) stage.append(make('p','trip-timer',`${farmState.trip.emoji} Wyprawa trwa · pozostało <b id="primaryTimer">${formatTimer(Math.max(0,farmState.trip.ends - Date.now()))}</b>`)); if (farmState.trip) startFarmTimer(); }
  if (primaryGameTab === 'sklep') { const shop = make('div','shop-grid'); [['Smakołyk','🍎',8],['Lekarstwo','🩹',20],['Magiczny koc','🧸',35],['Bilet na wyprawę','🗺️',45]].forEach(([name,icon,cost]) => { const item = make('article','shop-item'); append(item,make('span','',icon),make('b','',name),make('small','',`${cost} 🐾`),button('Kup','primary-action',() => { if (farmState.coins < cost) return toast('Za mało monet.'); farmState.coins -= cost; saveFarm(); toast(`Kupiono: ${name}.`); renderPrimaryGame('farm'); })); shop.append(item); }); stage.append(shop); }
  if (farmState.tutorial) { const guide = make('div','primary-tutorial'); append(guide,make('b','🌟 Pierwszy krok'),make('span','',`Wybierz ${pet.name}, nakarm go, a potem wyślij na krótką wyprawę. Każda akcja buduje relację.`),button('Rozumiem','primary-action',() => { farmState.tutorial = false; saveFarm(); renderPrimaryGame('farm'); })); stage.append(guide); }
}
function renderHomesteadPanel(stage) { clear(stage); const phase = homesteadPhase(); append(stage,primaryHeader('Gospodarstwo',`Produkuj, rozbudowuj i handluj · ${phase[0]} ${phase[1]}`,'🌾',homesteadState.coins,'🌾','GOSPODARSTWO · GŁÓWNA GRA')); const stats = make('div','homestead-stats'); append(stats,make('span','',`🧺 Koszyk ${homesteadState.basket.length}/${homesteadState.capacity}`),make('span','',`🏠 ${homesteadState.building} · poziom ${homesteadState.buildingLevel}`),make('span','',`🌱 Zboże ${homesteadState.grain}`)); stage.append(stats); const farmyard = make('div','homestead-yard'); append(farmyard,make('span','yard-building','🏠'),make('span','yard-windmill','🌬️'),make('span','yard-scarecrow','🧑‍🌾')); Object.entries(homesteadState.animals).forEach(([id,animal]) => { const data = HOMESTEAD_ANIMALS[Number(id)]; const card = make('article',`homestead-animal${animal.unlocked ? '' : ' locked'}`); append(card,make('span','',animal.unlocked ? animal.emoji : '🔒'),make('b','',animal.unlocked ? data[0] : '???'),make('small','',animal.unlocked ? `${data[3]} · co ${data[4]} min` : `${data[5]} 🌾`),button(animal.unlocked ? 'Zbierz' : 'Odblokuj','primary-action',() => animal.unlocked ? collectAnimal(id) : unlockAnimal(id))); farmyard.append(card); }); stage.append(farmyard); const controls = make('div','primary-actions-row'); append(controls,button('🧺 Zbierz wszystko','primary-action',collectAllAnimals),button('🛒 Sprzedaj koszyk','primary-action',sellBasket),button(`🏗️ Ulepsz (${80 * homesteadState.buildingLevel} 🌾)`,'primary-action',upgradeHomestead)); stage.append(controls); const log = make('div','homestead-log'); append(log,make('b','', 'Dziennik gospodarstwa')); homesteadState.log.slice(0,5).forEach(entry => log.append(make('p','',entry))); stage.append(log); if (homesteadState.tutorial) { const guide = make('div','primary-tutorial'); append(guide,make('b','🌾 Samouczek gospodarstwa'),make('span','',`Klikaj „Zbierz”, sprzedawaj produkty i ulepszaj budynek. Rano produkcja jest szybsza, a nocą wolniejsza.`),button('Zaczynamy','primary-action',() => { homesteadState.tutorial = false; saveHomestead(); renderPrimaryGame('homestead'); })); stage.append(guide); } }
function renderPrimaryGame(type) { const stage = $('#gameStage'); if (!stage) return; $('#gameModal').classList.remove('hidden'); $('#modalKicker').textContent = type === 'farm' ? 'ZWIERZAKOWA FARMA' : 'GOSPODARSTWO'; $('#modalTitle').textContent = type === 'farm' ? 'Twoja farma przygód' : 'Twoje gospodarstwo'; $('#gameInstruction').textContent = 'Gra zapisuje się lokalnie. Możesz wrócić do niej w dowolnym momencie.'; $('#gameProgress').firstElementChild.style.width = '100%'; $('#gameScore').textContent = type === 'farm' ? `${farmState.coins} 🐾` : `${homesteadState.coins} 🌾`; type === 'farm' ? renderFarmPanel(stage) : renderHomesteadPanel(stage); $('#gameMessage').textContent = ''; }
function renderAnimals() { const animals = unlockedAnimals(); const root = $('#animalCollection'); clear(root); $('#collectionCount').textContent = `${animals.length} / ${ANIMALS.length}`; ANIMALS.forEach(animal => { const unlocked = animals.some(item => item.id === animal.id); const card = button('',`animal-card${unlocked ? ' unlocked' : ''}${progress.selectedAnimal === animal.id && unlocked ? ' selected' : ''}`,() => { if (!unlocked) { toast(`Ten towarzysz pojawi się po ${animal.threshold} XP.`); return; } progress.selectedAnimal = animal.id; saveProgress(); renderSeason(); renderAnimals(); playTone('tap'); }); card.disabled = !unlocked; append(card,make('span','animal-emoji',unlocked ? animal.emoji : '🔒'),make('b','',unlocked ? animal.name : '???'),make('small','',unlocked ? (progress.selectedAnimal === animal.id ? 'Towarzyszy Ci' : 'Wybierz') : `${animal.threshold} XP`)); root.append(card); }); }
function randomQuestion(source, count) { return shuffle(source).slice(0,count); }
function openGame(type) { if (type === 'farm' || type === 'homestead') { primaryGameTab = type === 'farm' ? 'farm' : 'farm'; renderPrimaryGame(type); playTone('tap'); return; } gameState = {type, questions:[], index:0, score:0, answered:false, memoryCards:[], memoryOpen:[], memoryMatched:[], attempts:0, wordLetters:[], wordAnswer:'', wordUsed:[]}; $('#gameModal').classList.remove('hidden'); playTone('tap'); if (type === 'memory') { setupMemory(); return; } if (type === 'word') { gameState.questions = randomQuestion(WORDS,5); setupWord(); return; } gameState.questions = randomQuestion(type === 'quiz' ? QUIZ : type === 'truth' ? TRUTH : type === 'mathpets' ? MATH_PETS : SPRINT, type === 'sprint' ? 8 : type === 'mathpets' ? MATH_PETS.length : 10); renderQuestion(); }
function closeGame() { $('#gameModal').classList.add('hidden'); }
function updateGameProgress(total) { $('#gameScore').textContent = `${gameState.score} pkt`; $('#gameProgress').firstElementChild.style.width = `${total ? gameState.index / total * 100 : 0}%`; }
function renderQuestion() { const current = gameState.questions[gameState.index]; const isTruth = gameState.type === 'truth'; $('#modalKicker').textContent = gameState.type === 'quiz' ? 'MISJA: QUIZ' : gameState.type === 'truth' ? 'MISJA: FAKT CZY FIKCJA' : gameState.type === 'mathpets' ? 'NAGRODY: ZWIERZAKI' : 'MATEMATYCZNY SPRINT'; $('#modalTitle').textContent = current.q; $('#gameInstruction').textContent = gameState.type === 'mathpets' ? `Pytanie ${gameState.index + 1} z ${gameState.questions.length}. Każda poprawna odpowiedź przybliża Cię do nowego zwierzaka.` : `Pytanie ${gameState.index + 1} z ${gameState.questions.length}. Pomyśl chwilę — po odpowiedzi zobaczysz wyjaśnienie.`; updateGameProgress(gameState.questions.length); const stage = $('#gameStage'); clear(stage); const answers = isTruth ? [{label:'Prawda',value:'true'},{label:'Fałsz',value:'false'}] : shuffle(current.a).map(value => ({label:value,value})); const answerBox = make('div','answers'); answers.forEach(answer => answerBox.append(button(answer.label,'answer-button',() => answerQuestion(answer.value)))); stage.append(answerBox); $('#gameMessage').replaceChildren(); }
function answerQuestion(value) { if (gameState.answered) return; gameState.answered = true; const current = gameState.questions[gameState.index]; const correctValue = gameState.type === 'truth' ? String(current.c) : current.c; const correct = value === correctValue; document.querySelectorAll('.answer-button').forEach(node => { node.disabled = true; if (node.textContent === correctValue || node.dataset.answer === correctValue) node.classList.add('correct'); if (!correct && node.textContent === value) node.classList.add('wrong'); }); if (correct) { gameState.score += 1; playTone('success'); } else playTone('wrong'); $('#gameScore').textContent = `${gameState.score} pkt`; const message = $('#gameMessage'); clear(message); const feedback = make('span',correct ? 'feedback-good' : 'feedback-help',correct ? 'Dobrze! ' : 'Zapamiętaj: '); const next = button(gameState.index + 1 === gameState.questions.length ? 'Zobacz wynik →' : 'Następne →','next-button',() => { gameState.index += 1; gameState.answered = false; gameState.index < gameState.questions.length ? renderQuestion() : finishGame(); }); append(message,feedback,document.createTextNode(current.e),next); }
function setupMemory() { const cards = shuffle(PAIRS.flatMap(pair => [{pair:pair[0],text:pair[0],icon:pair[2],kind:'a'},{pair:pair[0],text:pair[1],icon:pair[2],kind:'b'}])); gameState.memoryCards = cards; $('#modalKicker').textContent = 'MISJA: LABORATORIUM PAR'; $('#modalTitle').textContent = 'Połącz pojęcie z jego znaczeniem'; $('#gameInstruction').textContent = 'Odkrywaj po dwie karty. Bez limitu czasu — sprawdź, czy pobijesz własny rekord prób.'; $('#gameScore').textContent = '0 / 8 par'; $('#gameProgress').firstElementChild.style.width = '0%'; const stage = $('#gameStage'); clear(stage); const board = make('div','memory-board'); cards.forEach((card,index) => { const node = button('','memory-card',() => flipMemory(index)); node.dataset.index = String(index); const inner = make('span','memory-inner'); const front = make('span','memory-front','?'); const back = make('span','memory-back'); append(back,make('b','',card.icon),make('small','',card.text)); append(inner,front,back); node.append(inner); board.append(node); }); stage.append(board); $('#gameMessage').textContent = 'Znajdź wszystkie 8 par.'; }
function flipMemory(index) { if (gameState.memoryOpen.length >= 2 || gameState.memoryMatched.includes(index) || gameState.memoryOpen.includes(index)) return; gameState.memoryOpen.push(index); const node = document.querySelector(`.memory-card[data-index="${index}"]`); node?.classList.add('flipped'); playTone('tap'); if (gameState.memoryOpen.length < 2) return; gameState.attempts += 1; const [first,second] = gameState.memoryOpen; const one = gameState.memoryCards[first], two = gameState.memoryCards[second]; const match = one.pair === two.pair && one.kind !== two.kind; if (match) { gameState.memoryMatched.push(first,second); gameState.memoryOpen = []; document.querySelector(`.memory-card[data-index="${first}"]`)?.classList.add('matched'); document.querySelector(`.memory-card[data-index="${second}"]`)?.classList.add('matched'); gameState.score = gameState.memoryMatched.length / 2; $('#gameScore').textContent = `${gameState.score} / 8 par`; $('#gameProgress').firstElementChild.style.width = `${gameState.memoryMatched.length / gameState.memoryCards.length * 100}%`; playTone('success'); if (gameState.memoryMatched.length === gameState.memoryCards.length) setTimeout(finishGame,350); } else { playTone('wrong'); setTimeout(() => { gameState.memoryOpen.forEach(item => document.querySelector(`.memory-card[data-index="${item}"]`)?.classList.remove('flipped')); gameState.memoryOpen = []; },650); } }
function setupWord() { const current = gameState.questions[gameState.index]; gameState.wordLetters = shuffle([...current.word]); gameState.wordAnswer = ''; gameState.wordUsed = []; $('#modalKicker').textContent = 'MISJA: SŁOWNY TROP'; $('#modalTitle').textContent = `Hasło ${gameState.index + 1} z ${gameState.questions.length}`; $('#gameInstruction').textContent = current.hint; $('#gameScore').textContent = `${gameState.score} pkt`; $('#gameProgress').firstElementChild.style.width = `${gameState.index / gameState.questions.length * 100}%`; renderWordBoard(); }
function renderWordBoard() { const stage = $('#gameStage'); clear(stage); const board = make('div','word-board'); const built = make('div','built-word',gameState.wordAnswer || '—'); built.setAttribute('aria-label','Ułożone hasło'); const bank = make('div','letter-bank'); gameState.wordLetters.forEach((letter,index) => { const used = gameState.wordUsed.includes(index); const node = button(letter,'letter-button',() => { if (used) return; gameState.wordUsed.push(index); gameState.wordAnswer += letter; renderWordBoard(); }); node.disabled = used; if (used) node.classList.add('used'); bank.append(node); }); const actions = make('div','word-actions'); const erase = button('Cofnij','secondary-action',() => { const index = gameState.wordUsed.pop(); if (index !== undefined) gameState.wordAnswer = gameState.wordAnswer.slice(0,-1); renderWordBoard(); }); const check = button('Sprawdź','next-button',checkWord); append(actions,erase,check); append(board,built,bank,actions); stage.append(board); $('#gameMessage').textContent = 'Ułóż wyraz, a potem sprawdź odpowiedź.'; }
function checkWord() { const current = gameState.questions[gameState.index]; if (gameState.wordAnswer !== current.word) { $('#gameMessage').textContent = 'To jeszcze nie to. Skorzystaj z podpowiedzi i spróbuj ponownie.'; playTone('wrong'); return; } gameState.score += 1; playTone('success'); const message = $('#gameMessage'); clear(message); append(message,make('span','feedback-good','Dobrze! '),document.createTextNode(`Hasło „${current.word}” jest poprawne.`),button(gameState.index + 1 === gameState.questions.length ? 'Zobacz wynik →' : 'Następne →','next-button',() => { gameState.index += 1; gameState.index < gameState.questions.length ? setupWord() : finishGame(); })); document.querySelectorAll('.letter-button,.word-actions button').forEach(node => node.disabled = true); }
function finishMathPets(score,max) { const before = unlockedAnimals().length; const reward = score === max ? 40 : score >= 3 ? 20 : 8; progress.gameXp += reward; progress.gameHistory = {...progress.gameHistory,mathpets:{sessions:(gameHistory('mathpets').sessions || 0) + 1,best:Math.max(gameHistory('mathpets').best || 0,score),lastReward:rewardToday()}}; progress.sessionCount += 1; saveProgress(); const after = unlockedAnimals(); const newPet = after.length > before ? after[after.length - 1] : null; const stage = $('#gameStage'); clear(stage); const result = make('div','result-card'); append(result,make('div','result-stars',score === max ? '🐾🌟🐾' : score >= 3 ? '🐾🌟' : '🐾'),make('strong','',score === max ? 'Matematyczny mistrz!' : 'Dobry tropiciel!'),make('span','',`Zdobywasz +${reward} XP.`)); if (newPet) result.append(make('p','feedback-good',`Nowy towarzysz dołącza do szlaku: ${newPet.emoji} ${newPet.name}!`)); stage.append(result); $('#gameProgress').firstElementChild.style.width = '100%'; $('#modalKicker').textContent = 'NAGRODA ODEBRANA'; $('#modalTitle').textContent = `Wynik: ${score}/${max}`; $('#gameMessage').textContent = newPet ? `Odblokowano ${newPet.name}!` : 'Zagraj ponownie, aby zebrać więcej XP.'; renderAll(); }
function finishGame() { const type = gameState.type; const max = type === 'memory' ? 8 : gameState.questions.length; const score = gameState.score; if (type === 'mathpets') return finishMathPets(score,max); $('#gameProgress').firstElementChild.style.width = '100%'; $('#modalKicker').textContent = 'SESJA UKOŃCZONA'; $('#modalTitle').textContent = `Wynik: ${score}/${max}`; const stage = $('#gameStage'); clear(stage); const result = make('div','result-card'); append(result,make('div','result-stars',score >= Math.ceil(max*.8) ? '🌟🌟🌟' : score >= Math.ceil(max*.5) ? '🌟🌟' : '🌟'),make('strong','',score >= Math.ceil(max*.8) ? 'Świetny wynik!' : 'Dobra próba!'),make('span','', 'Każda sesja ćwiczy pamięć, wiedzę i wytrwałość.')); stage.append(result); const reward = awardGame(type,score,max); const msg = $('#gameMessage'); clear(msg); msg.textContent = reward ? `Zdobywasz +${reward} XP za dzisiejszą sesję!` : 'Bonus XP na dziś został już odebrany. Możesz ćwiczyć dalej dla rekordu!'; renderAll(); }
function awardGame(type, score, max) { const today = rewardToday(); const history = gameHistory(type); let reward = 0; const oldKeys = {quiz:[S.quiz,S.quizXp,50],memory:[S.memory,S.memoryXp,30],truth:[S.truth,S.truthXp,25]}; if (oldKeys[type] && !bool(oldKeys[type][0])) { const [completeKey,xpKey,cap] = oldKeys[type]; const legacyReward = Math.max(type === 'memory' ? 10 : 4,Math.round(score / max * cap)); set(completeKey,true); set(xpKey,legacyReward); reward = legacyReward; }
  if (!reward && history.lastReward !== today) { reward = Math.max(4,Math.round(score / Math.max(max,1) * (type === 'memory' ? 18 : 14))); progress.gameXp += reward; }
  progress.gameHistory = {...progress.gameHistory,[type]:{sessions:history.sessions + 1,best:Math.max(history.best,score),lastReward:reward ? today : history.lastReward}}; progress.sessionCount += 1; saveProgress(); playTone('success'); return reward; }

function badgeData() { const completed = completedTasks().length, lessons = completedLessons().length, games = progress.sessionCount, animals = unlockedAnimals().length, xp = totalXp(); return [{icon:'🌱',name:'Pierwszy krok',desc:'Ukończ 1 zestaw',ok:completed >= 1},{icon:'📚',name:'Czytelnik misji',desc:'Ukończ 10 zestawów',ok:completed >= 10},{icon:'🎯',name:'Plan na medal',desc:'Oznacz 10 lekcji',ok:lessons >= 10},{icon:'🧠',name:'Gracz wiedzy',desc:'Zagraj 3 sesje',ok:games >= 3},{icon:'🔥',name:'W rytmie nauki',desc:'Zbierz 150 XP',ok:xp >= 150},{icon:'🦊',name:'Przyjaciel szlaku',desc:'Odblokuj 3 zwierzęta',ok:animals >= 3},{icon:'⭐',name:'Mistrz małych kroków',desc:'Ukończ 25 zestawów',ok:completed >= 25},{icon:'🏔️',name:'Legenda szlaku',desc:'Zbierz 500 XP',ok:xp >= 500}]; }
function renderProgress() { const xp = totalXp(), level = Math.floor(xp / 50) + 1, rank = level >= 12 ? 'Legenda Szlaku' : level >= 8 ? 'Mistrz Odkryć' : level >= 4 ? 'Praktyk' : 'Odkrywca'; const until = level * 50 - xp; $('#progressRank').textContent = rank; $('#progressLevel').textContent = `Poziom ${level} · następny poziom za ${Math.max(0,until)} XP`; $('#progressXp').textContent = xp; $('#levelProgressBar').style.width = `${xp % 50 / 50 * 100}%`; $('#progressLessons').textContent = completedLessons().length; $('#progressTasks').textContent = completedTasks().length; $('#progressGames').textContent = progress.sessionCount; $('#progressAnimals').textContent = unlockedAnimals().length; const badges = badgeData(); $('#badgeCount').textContent = `${badges.filter(item => item.ok).length} / ${badges.length}`; const root = $('#badgesGrid'); clear(root); badges.forEach(badge => { const item = make('article',`badge${badge.ok ? ' unlocked' : ''}`); append(item,make('span','badge-icon',badge.ok ? badge.icon : '🔒')); const copy = make('div'); append(copy,make('b','',badge.name),make('small','',badge.ok ? 'Odblokowano!' : badge.desc)); item.append(copy); root.append(item); }); }
function renderMore() { const note = get(S.notebook,''); $('#notebookText').value = typeof note === 'string' ? note : ''; $('#notebookCount').textContent = `${$('#notebookText').value.length} / 3000`; $('#religionState').textContent = get(S.religion,false) ? 'Włączone' : 'Wyłączone'; $('#themeState').textContent = preferences.season === 'auto' ? 'Auto' : SEASONS[preferences.season].label; $('#motionState').textContent = preferences.animations ? 'Włączone' : 'Wyłączone'; }
function renderAll() { renderSeason(); renderPlan(); renderSubjects(); renderTasks(); renderGames(); renderProgress(); renderHeader(); renderMore(); }
function switchView(view) { activeView = view; document.querySelectorAll('.view').forEach(node => node.classList.toggle('active',node.id === `view-${view}`)); document.querySelectorAll('.tab').forEach(node => { const selected = node.dataset.view === view; node.classList.toggle('active',selected); node.setAttribute('aria-selected',String(selected)); }); if (view === 'tasks') { renderSubjects(); renderTasks(); } if (view === 'games') { renderGames(); renderSeason(); } if (view === 'progress') renderProgress(); if (view === 'more') renderMore(); window.scrollTo({top:0,behavior:preferences.animations ? 'smooth' : 'auto'}); }

function openSeasonPicker() { const root = $('#seasonOptions'); clear(root); Object.entries(SEASONS).forEach(([key,season]) => { const selected = preferences.season === key; const option = button('',`season-option${selected ? ' selected' : ''}`,() => { preferences.season = key; savePreferences(); $('#seasonModal').classList.add('hidden'); renderAll(); toast(key === 'auto' ? 'Motyw będzie dopasowany automatycznie.' : `Wybrano: ${season.name}.`); }); append(option,make('span','option-emoji',season.emoji),(() => { const copy = make('span'); append(copy,make('b','',season.name),make('small','',season.description)); return copy; })()); root.append(option); }); $('#seasonModal').classList.remove('hidden'); }
function openEditor() { const day = effectiveDays().find(item => item.key === selectedDay) || DAYS[0]; const fields = $('#editorFields'); clear(fields); day.lessons.forEach((lesson,index) => { const field = make('fieldset','editor-field'); field.append(make('legend','',`${lesson[0]}–${lesson[1]}`)); [['subject',lesson[2],'Przedmiot'],['teacher',lesson[3],'Nauczyciel'],['room',lesson[4],'Sala']].forEach(([key,value,label]) => { const input = document.createElement('input'); input.required = key === 'subject'; input.value = value; input.dataset.editorKey = key; input.dataset.index = String(index); input.setAttribute('aria-label',label); field.append(input); }); fields.append(field); }); $('#planEditorModal').classList.remove('hidden'); }
function saveEditor() { const original = effectiveDays().find(item => item.key === selectedDay) || DAYS[0]; const day = JSON.parse(JSON.stringify(original)); document.querySelectorAll('[data-editor-key]').forEach(input => { const index = Number(input.dataset.index); const position = input.dataset.editorKey === 'subject' ? 2 : input.dataset.editorKey === 'teacher' ? 3 : 4; day.lessons[index][position] = input.value.trim() || day.lessons[index][position]; }); set(S.customPlan,effectiveDays().map(item => item.key === day.key ? day : item)); $('#planEditorModal').classList.add('hidden'); toast('Plan zapisany na tym urządzeniu.'); renderPlan(); }
function restorePlan() { if (!confirm('Przywrócić przykładowy plan? Własne edycje planu zostaną usunięte, ale XP i gry pozostaną.')) return; localStorage.removeItem(S.customPlan); $('#planEditorModal').classList.add('hidden'); renderPlan(); toast('Przywrócono przykładowy plan.'); }
function resetAll() { if (!confirm('Czy na pewno wyzerować cały postęp, gry, odznaki i ustawienia? Plan można zachować osobno.')) return; [S.tasks,S.lessons,S.profile,S.quiz,S.quizXp,S.memory,S.memoryXp,S.truth,S.truthXp,S.notebook,S.customPlan,S.progress,S.preferences,S.farm,S.homestead].forEach(key => localStorage.removeItem(key)); progress = {...DEFAULT_PROGRESS}; preferences = {season:'auto',animations:true}; farmState = loadFarm(); homesteadState = loadHomestead(); toast('Postęp został wyzerowany.'); renderAll(); }
function prepareFeedback(event) { event.preventDefault(); const name = $('#feedbackName').value.trim(); const message = $('#feedbackMessage').value.trim(); if (!message) return; const body = [`Opinia z aplikacji Plan Lekcji${name ? `\nOd: ${name}` : ''}`, '', message, '', 'Wiadomość została przygotowana lokalnie w aplikacji Plan Lekcji.'].join('\n'); window.location.href = `mailto:ronoc2020@gmail.com?subject=${encodeURIComponent('Aplikacja Plan Lekcji')}&body=${encodeURIComponent(body)}`; toast('Otwieram program pocztowy z przygotowaną wiadomością.'); }

function bindEvents() {
  document.querySelectorAll('.tab').forEach(node => node.addEventListener('click',() => switchView(node.dataset.view)));
  document.querySelectorAll('.profile-option').forEach(node => node.addEventListener('click',() => { set(S.profile,node.dataset.profile); renderHeader(); toast('Powitanie zapisane.'); playTone('success'); }));
  document.querySelectorAll('.filter-button').forEach(node => node.addEventListener('click',() => { activeFilter = node.dataset.filter; document.querySelectorAll('.filter-button').forEach(buttonNode => buttonNode.classList.toggle('active',buttonNode === node)); renderTasks(); }));
  $('#taskSearch').addEventListener('input',event => { searchQuery = event.target.value; renderTasks(); });
  $('#religionToggle').addEventListener('click',() => { set(S.religion,!get(S.religion,false)); renderPlan(); renderMore(); });
  $('#themeSettingsButton').addEventListener('click',openSeasonPicker); $('#chooseSeasonButton').addEventListener('click',openSeasonPicker); $('#seasonChip').addEventListener('click',openSeasonPicker);
  $('#motionToggle').addEventListener('click',() => { preferences.animations = !preferences.animations; savePreferences(); renderSeason(); renderMore(); toast(preferences.animations ? 'Łagodne animacje są włączone.' : 'Animacje są zatrzymane.'); });
  $('#resetPlanButton').addEventListener('click',() => { if (confirm('Przywrócić przykładowy plan i wyczyścić zaznaczenia lekcji?')) { localStorage.removeItem(S.lessons); localStorage.removeItem(S.customPlan); renderPlan(); toast('Przywrócono przykładowy plan.'); } });
  $('#resetAllButton').addEventListener('click',resetAll); $('#resetButton').addEventListener('click',resetAll); $('#soundToggle').addEventListener('click',() => { set(S.sound,!bool(S.sound)); renderHeader(); playTone('success'); toast(bool(S.sound) ? 'Dźwięki włączone.' : 'Dźwięki wyłączone.'); });
  $('#closeGameButton').addEventListener('click',closeGame); $('#gameModal').addEventListener('click',event => { if (event.target.id === 'gameModal') closeGame(); });
  $('#closeTaskButton').addEventListener('click',() => $('#taskModal').classList.add('hidden')); $('#taskModal').addEventListener('click',event => { if (event.target.id === 'taskModal') $('#taskModal').classList.add('hidden'); }); $('#taskHintButton').addEventListener('click',() => { const stage = $('#taskStage'); stage.classList.toggle('show-hints'); $('#taskHintButton').textContent = stage.classList.contains('show-hints') ? 'Ukryj podpowiedzi' : 'Pokaż podpowiedzi'; }); $('#finishTaskButton').addEventListener('click',finishTask);
  $('#closeSeasonButton').addEventListener('click',() => $('#seasonModal').classList.add('hidden')); $('#seasonModal').addEventListener('click',event => { if (event.target.id === 'seasonModal') $('#seasonModal').classList.add('hidden'); });
  $('#editPlanButton').addEventListener('click',openEditor); $('#closeEditorButton').addEventListener('click',() => $('#planEditorModal').classList.add('hidden')); $('#restoreDayButton').addEventListener('click',restorePlan); $('#planEditorForm').addEventListener('submit',event => { event.preventDefault(); saveEditor(); });
  $('#notebookText').addEventListener('input',event => $('#notebookCount').textContent = `${event.target.value.length} / 3000`); $('#saveNotebook').addEventListener('click',() => { set(S.notebook,$('#notebookText').value); toast('Notatka zapisana na tym urządzeniu.'); playTone('success'); }); $('#feedbackForm').addEventListener('submit',prepareFeedback);
  document.addEventListener('keydown',event => { if (event.key === 'Escape') { closeGame(); $('#taskModal').classList.add('hidden'); $('#seasonModal').classList.add('hidden'); $('#planEditorModal').classList.add('hidden'); } });
}

migrateLegacyState(); if (localStorage.getItem(S.sound) === null) set(S.sound,true); bindEvents(); renderAll();
